### ISSUE TITLE
Support Spring Boot v1.5.12.RELEASE

### ISSUE THREAD

**Issue by leizhiyuan** [alipay/sofa-boot#106]
Maybe Update to Spring Boot 2.0 need more test, we can update to v1.5.12 first.

1.4.x is no longer maintained from Spring Boot Member.

**Comment by QilongZhang** [comment]
https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-1.5-Release-Notes  i refer to Spring Boot 1.5.x release note,  some classes used by current SOFABoot have been deprecated, it needs some compatible works when using 1.5.x Spring Boot.  Maybe we should upgrade to 2.x. , and the timeline would be determined after evaluation.
