### ISSUE TITLE
数据库分库分表如何使用？

### ISSUE THREAD

**Issue by zhengjieyuan** [alipay/sofa-boot#107]
请问数据库分库分表如何使用？ 是否有demo？

**Comment by QilongZhang** [comment]
@zhengjieyuan  欢迎关注，目前 SOFABoot 还没有开源数据中间件组件， SOFABoot 基于 Spring Boot 提供的功能扩展详见[文档链接](http://www.sofastack.tech/sofa-boot/docs/Home) 。 在 SOFABoot 和 Spring Boot 开发中使用数据库也没有差别。

**Comment by zhengjieyuan** [comment]
数据库中间件组件什么时候能开源呢？ 比较迫切需要这个组件。

**Comment by QilongZhang** [comment]
Issue 将被关闭，如有其它问题，请重新打开。 @zhengjieyuan
