### ISSUE TITLE
spring mvc 如何通过xml的方式引用sofa-boot-rpc里面发布的服务？

### ISSUE THREAD

**Issue by wangxiaotao00** [alipay/sofa-boot#116]
请问spring mvc 如何通过xml的方式引用sofa-boot-rpc里面发布的服务？

**Comment by QilongZhang** [comment]
@wangxiaotao00  目前推荐的环境是 SOFABoot，如果你希望在 Spring MVC 中使用 xml 引用服务，需要在工程中添加 SOFABoot 的依赖包，引用方式是一样，参考 [文档](https://github.com/alipay/sofa-rpc/wiki/Programing-SOFA-BOOT)
