### ISSUE TITLE
SOFABoot HealthCheck disable the actuator exposed endpoints

### ISSUE THREAD

**Issue by guanchao-yang** [alipay/sofa-boot#118]
### Background

The Spring Boot Actuator expose some endpoints like this [in 1.4.2.RELEASE](https://docs.spring.io/spring-boot/docs/1.4.2.RELEASE/reference/html/production-ready-endpoints.html), but in application exposes these endpoints have secure proplems and may cause secure danger

### Solution

In HealthCheck Starter disable the actuator endpoints and only enable these endpoints.

```
/health
/health/readiness
/sofaboot/versions
```
But in  SOFABoot we provide config to enable the closed actuator endpoints, such as in SOFABoot configure `endpoints.heapdump.enabled=true` to enable actuator `heapdump` endpoints.The enabled configuration should be compatible with actuator.

> When upgrade [Spring Boot to 2.X](https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-endpoints.html#production-ready-endpoints-exposing-endpoints), the exposed endpoints are onle `info`，we should consider the compatible.

**Comment by QilongZhang** [comment]
@guanchao-yang  Currently,  SOFABoot inherits original configuration from Spring Boot. The users can configure such as `endpoints.xxx.enabled` to  enable or disable specified endpoint.  Maybe it's not convenient to disable all default endpoints explicitly via SOFABoot，we should follow the usage habit of Spring Boot. They should be configured by user-self.

**Comment by guanchao-yang** [comment]
@QilongZhang We do this only for secure consider and when user use SOFABoot we provide a  secure environment by default

**Comment by QilongZhang** [comment]
Upgrade Spring Boot version to 1.5.16.RELEASE in SOFABoot v2.5.0，and the sensitive  endpoints have been disabled.

**Comment by QilongZhang** [comment]
https://github.com/alipay/sofa-build/pull/1
