### ISSUE TITLE
The sofa.ark.version version issue for building

### ISSUE THREAD

**Issue by zorkeAccount** [alipay/sofa-boot#120]
Please modify <sofa.ark.version>0.4.0-SNAPSHOT</sofa.ark.version> to <sofa.ark.version>0.4.0</sofa.ark.version> because the maven central repository is 0.4.0 not the SNAPSHOT

**Comment by QilongZhang** [comment]
@zorkeAccount  thanks,  the master branch is on-developing and have not timely modify it yet. I would update it later, also you can pr if you do not mind it

**Comment by QilongZhang** [comment]
@zorkeAccount  thanks again. I have upgraded  ark version and would close  this issue.

**Comment by zorkeAccount** [comment]
@QilongZhang ok
