### ISSUE TITLE
the method of init() is never used？

### ISSUE THREAD

**Issue by larrychao** [alipay/sofa-boot#134]
hi，
the method of  init() in JvmServiceConumer is never used or the method can not find the reference,
but when i install the sofaboot-sample-with-isle can print the result of init() ,
why?

**Comment by caojie09** [comment]
[used here.](https://github.com/alipay/sofa-boot/blob/master/sofaboot-samples/sofaboot-sample-with-isle/service-consumer/src/main/resources/META-INF/spring/service-consumer.xml#L13)

**Comment by larrychao** [comment]
THX
