### ISSUE TITLE
where is sofa-jarslink-ark-starter ?

### ISSUE THREAD

**Issue by larrychao** [alipay/sofa-boot#135]
the SOFA DOC, has the sample code for how to use jarslink : http://www.sofastack.tech/sofa-boot/docs/sofa-jarslink-jarslink-app-demo ,

    <dependency>
        <groupId>com.alipay.sofa</groupId>
        <artifactId>sofa-jarslink-ark-starter</artifactId>
        <classifier>ark-plugin</classifier>
        <version>2.0.0-SNAPSHOT</version>
    </dependency>
we can not find the sofa-jarslink-ark-starter

**Comment by straybirdzls** [comment]
I just check, the jar is not released to maven center, I will release it soon.

Sorry for the inconvenience. For quick use, please clone https://github.com/alipay/sofa-jarslink.git to local and run `maven clean install`

**Comment by straybirdzls** [comment]
You can find the jar here: https://oss.sonatype.org/content/repositories/snapshots/com/alipay/sofa/sofa-jarslink-ark-starter/

please add the following repo:

```
<repositories>
                <repository>
                    <snapshots>
                        <enabled>true</enabled>
                    </snapshots>
                    <id>maven-snapshot</id>
                    <url>https://oss.sonatype.org/content/repositories/snapshots</url>
                </repository>
            </repositories>
            <pluginRepositories>
                <pluginRepository>
                    <snapshots>
                        <enabled>true</enabled>
                    </snapshots>
                    <id>maven-snapshot</id>
                    <url>https://oss.sonatype.org/content/repositories/snapshots</url>
                </pluginRepository>
            </pluginRepositories>
```

**Comment by larrychao** [comment]
Thank you ,I just do the same like your help

**Comment by straybirdzls** [comment]
@larrychao What about the version of sofaboot?

**Comment by larrychao** [comment]
2.4.0,                is it too old?

**Comment by larrychao** [comment]
the context of pom is 👍 
`<parent>
		<groupId>com.alipay.sofa</groupId>
		<artifactId>sofaboot-dependencies</artifactId>
		<version>2.4.0</version>
	</parent>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
		<java.version>1.8</java.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>com.alipay.sofa</groupId>
			<artifactId>sofa-jarslink-ark-starter</artifactId>
			<classifier>ark-plugin</classifier>
			<version>2.0.0-SNAPSHOT</version>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>`

**Comment by straybirdzls** [comment]
@larrychao jarslink rely on sofa-ark [0.4.0](https://github.com/alipay/sofa-ark/releases/tag/v0.4.0) 
 
two way to fix:

1. use sofaboot  2.5.0-SNAPSHOT instead of 2.4.0
2. add `<version>0.4.0</version>` to  sofa-ark-maven-plugin

**Comment by larrychao** [comment]
ok 
where is sofaboot 2.5.0-SNAPSHOT ? can you add it to repo?

**Comment by straybirdzls** [comment]
here: https://oss.sonatype.org/content/repositories/snapshots/com/alipay/sofa/sofaboot-dependencies/2.5.0-SNAPSHOT/

**Comment by larrychao** [comment]
@straybirdzls I also can not find the <version>0.4.0</version> to sofa-ark-maven-plugin,sorry

**Comment by larrychao** [comment]
@straybirdzls THX . I find the 0.4.0 to sofa-ark-maven-plugin

**Comment by larrychao** [comment]
@straybirdzls 
I use  sofaboot 2.5.0-SNAPSHOT and 0.4.0 to sofa-ark-maven-plugin but failed for un either

the run log is 👍 
java -jar jarslinkdemo-0.0.1-SNAPSHOT-executable-ark.jar 
Sofa-Middleware-Log SLF4J : Actual binding is of type [ com.alipay.sofa.ark Log4j ]
log4j:WARN No appenders could be found for logger (com.alipay.sofa.common.log).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Sofa-Middleware-Log SLF4J : Actual binding is of type [ com.alipay.sofa.jarslink Log4j ]
log4j:WARN No appenders could be found for logger (com.alipay.sofa.common.log).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                        

2018-07-19 21:02:52.595  INFO 14915 --- [           main] c.t.j.JarslinkdemoApplication            : Starting JarslinkdemoApplication on zhaoleideMacBook-Pro.local with PID 14915 (/Users/zhaolei/CODE/TestCode/jarslinkdemo/target/jarslinkdemo-0.0.1-SNAPSHOT-executable-ark.jar started by zhaolei in /Users/zhaolei/CODE/TestCode/jarslinkdemo/target)
2018-07-19 21:02:52.598  INFO 14915 --- [           main] c.t.j.JarslinkdemoApplication            : No active profile set, falling back to default profiles: default
2018-07-19 21:02:52.651  INFO 14915 --- [           main] s.c.a.AnnotationConfigApplicationContext : Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@6bc168e5: startup date [Thu Jul 19 21:02:52 CST 2018]; root of context hierarchy
2018-07-19 21:02:53.226  INFO 14915 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Registering beans for JMX exposure on startup
2018-07-19 21:02:53.237  INFO 14915 --- [           main] c.t.j.JarslinkdemoApplication            : Started JarslinkdemoApplication in 0.928 seconds (JVM running for 1.978)
Ark container started in 1795 ms.
2018-07-19 21:02:53.239  INFO 14915 --- [       Thread-1] s.c.a.AnnotationConfigApplicationContext : Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@6bc168e5: startup date [Thu Jul 19 21:02:52 CST 2018]; root of context hierarchy
2018-07-19 21:02:53.240  INFO 14915 --- [       Thread-1] o.s.j.e.a.AnnotationMBeanExporter        : Unregistering JMX-exposed beans on shutdown

**Comment by straybirdzls** [comment]
@larrychao Check form the log, the application started successfully 

```
Ark container started in 1795 ms.
```

I guess your springboot application is not a web-based application and there is not any non-daemon thread on your application, so after it started, it runs finished. 

You can try web-based spring boot application , then after the application started, it will keep alive.

**Comment by QilongZhang** [comment]
@larrychao   关于拉取 SNAPSHOT 包的仓库配置可以参考文档 http://www.sofastack.tech/sofa-boot/docs/sofa-ark-faq 
另外本 issue 反馈的应用启动成功之后自动退出也增加了faq，感谢反馈。
