### ISSUE TITLE
plugin使用 spring 注解问题

### ISSUE THREAD

**Issue by gaolloag** [alipay/sofa-boot#150]
SOFABoot发布 plugin ，注册的服务内是否可以使用 @Autowired @Service 进行模块间的调用

**Comment by QilongZhang** [comment]
@gaolloag  你说的plugin是指什么？

**Comment by gaolloag** [comment]
@QilongZhang 指的是 ark 包

**Comment by QilongZhang** [comment]
@gaolloag   spring boot 的正常功能都可以使用，是遇到什么问题了吗？

**Comment by gaolloag** [comment]
@QilongZhang 是的, <goal>ark-plugin</goal> 打包安装后，ark中有使用   @Autowired  AccountManager manager;
启动后有报  No qualifying bean of type 'com.account.manager.AccountManager' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)} 

ps:代码地址 https://github.com/gaolloag/sofa-account

**Comment by gaolloag** [comment]
@QilongZhang 我把 AccountManager 注册了 sofa:service 可以了，但这块不是很理解呢，为什么需要把AccountManager 也注册服务呢，我把service注册了服务，service 是调用的 manager模块。

**Comment by QilongZhang** [comment]
@gaolloag  看了你传的代码，不需要注册 sofa:service 也是正常运行的。你后面是不是修改了？

**Comment by gaolloag** [comment]
@

**Comment by gaolloag** [comment]
@QilongZhang 不注册  sofa:service  使用 @SofaReference 注解，会报：cant not find the corresponding JVM service

详细异常：java.lang.IllegalStateException: JVM Reference[interface com.account.service.AccountService#] cant not find the corresponding JVM service. Please check if there is a SOFA deployment publish the corresponding JVM service. If this exception occurred when the application starts up, please add Require-Module to SOFA deployment's MANIFEST.MF to indicate the startup dependency of SOFA modules.

**Comment by gaolloag** [comment]
@QilongZhang 另外，maven 的 plugin有两个 ，一个sofa-ark-maven-plugin 另一个是 sofa-ark-plugin-maven-plugin，两个版本的 configuration 也不同，如何选择呢？

**Comment by QilongZhang** [comment]
@gaolloag  代码更新下？ 现在你仓库的代码好像是不报错的，我访问的是 /api/account/create

**Comment by gaolloag** [comment]
@QilongZhang 实验场景是这样的：
sofa-account 工程是类原生的 spring boot 项目，然后 account-plugin模块打包，然后install 到maven仓库，目前我是发布到了我的本地仓库。
另外还有一个  sofa-demo 工程 代码库:https://github.com/gaolloag/sofa-demo 作为使用 account-plugin ark 包的工程 。

**Comment by QilongZhang** [comment]
@gaolloag  代码比较混乱，和ark  plugin没什么关系，代码中也没有引入ark plugin的。
```xml
        <dependency>
            <groupId>com.gl.sofa.account.plugin</groupId>
            <artifactId>account-plugin</artifactId>
            <version>1.0-SNAPSHOT</version>
            <!-- <classifier>ark-plugin</classifier>-->
        </dependency>
```
然后回答下，sofa:service/sofa:reference 的问题， sofa:service/sofa:reference 有两个使用场景：
+ 多应用合并部署时，跨应用之间服务调用
+ 同一个应用内部，多个 [sofa module](http://www.sofastack.tech/sofa-boot/docs/Modular-Development) 之间上下文相互隔离，代替 Autowire 注解完成依赖注入

最后，你的 Autowire 没有注入成功的原因是因为你依赖 AccountManager 的实现没有被扫描到。sofa-demo 中没有用到sofa module。之所以使用sofa:service/sofa:reference 可以注入服务成功，是因为在同一个模块中使用sofa:service/sofa:reference也是可以的，只是没有这个必要。

建议一开始先逐个熟悉 sofa-boot 的特性，例如上下文隔离，类隔离，jvm服务，不要把所有的东西杂糅在一起，有点混乱。

**Comment by gaolloag** [comment]
好的，我重新梳理一下概念。多有讨扰，请多包含。

**Comment by gaolloag** [comment]
@QilongZhang 好的，我重新梳理一下概念。多有讨扰，请多包含。

**Comment by QilongZhang** [comment]
@gaolloag  嗯，欢迎交流反馈~
