### ISSUE TITLE
sofa-jarslink-ark-starter 依赖没有找到啊

### ISSUE THREAD

**Issue by gaolloag** [alipay/sofa-boot#151]
sofa-jarslink-ark-starter 依赖没有找到啊

**Comment by QilongZhang** [comment]
@gaolloag  目前 Jarslink 2.0.0 还处于快照版本，它依赖的 SOFABoot 2.5.0 版本也将近期发布，目前需要引入 SOFABoot 2.5.0-SNAPSHOT 版本依赖。SNAPSHOT 包拉取需要特殊的配置，详细请参考[FAQ: 如何配置拉取 SNAPSHOT 依赖包](http://www.sofastack.tech/sofa-boot/docs/sofa-jarslink-faq). 也可以参考演示文档，[如何在 SOFABoot 中使用 Jarslink 2.0.0](http://www.sofastack.tech/sofa-boot/docs/sofa-jarslink-jarslink-app-demo)
