### ISSUE TITLE
模块化开发：启动模块依赖web子模块，web无法正常启动

### ISSUE THREAD

**Issue by Weibin-Zhang** [alipay/sofa-boot#160]
参考sofaboot-sample-with-isle项目，通过web模块提供web接口，背后依赖service模块的jvm服务，单独一个启动模块做应用生命周期管理。
模块识别、启动正常，服务访问正常，但是controller无法识别，web功能无法启动。
另外，用web模块做starter没有问题。

**Comment by QilongZhang** [comment]
@Weibin-Zhang   麻烦把你的 Demo 放在github上，贴上一个链接哈。

**Comment by caojie09** [comment]
SOFABoot 模块一般用于封装对外发布服务接口的具体实现，属于业务层，Controller 属于展现层内容，目前不支持在 SOFABoot 模块中定义Controller内容。

**Comment by khotyn** [comment]
@caojie09 可以提供一个带 Web 的例子，来给大家作为参考。

**Comment by Weibin-Zhang** [comment]
把starter放在web模块可以解决此问题。
但与isle的独立starter模式有点差异，建议提供一个带web功能的项目模板，方便用户快速上手。

**Comment by caojie09** [comment]
好的，我加下示例工程。

**Comment by QilongZhang** [comment]
@caojie09  添加完示例工程，在这里放一个link, 然后重新关闭哈。

**Comment by caojie09** [comment]
@Weibin-Zhang 这篇文章介绍的工程就包含 Web 模块： https://mp.weixin.qq.com/s/-7_wXRcvWpt6JwsBIOkQjA
