### ISSUE TITLE
sofa多模块项目，启动和测试模块，需要怎么样启动其他模块

### ISSUE THREAD

**Issue by Alfred-it** [alipay/sofa-boot#162]
所有模块都要在pom中引入吗
所有模块的spring配置文件 需要显示引入吗
求一个多模块的DEMO工程，含web core biz test common几个大模块的完整的DEMO工程

**Comment by caojie09** [comment]
> 所有模块都要在pom中引入吗?

需要引入，SOFABoot 是从 classpath 扫描 SOFABoot 模块的，需要保证 SOFABoot 模块在应用 classpath。

> 所有模块的spring配置文件需要显示引入吗?

不需要，SOFABoot 会自动加载 SOFABoot 模块 META-INF/spring 目录下的配置文件，无需显示引入， SOFABoot 模块定义见: [http://www.sofastack.tech/sofa-boot/docs/SOFABoot-Module](http://www.sofastack.tech/sofa-boot/docs/SOFABoot-Module) 。

> 求一个多模块的DEMO工程，含web core biz test common几个大模块的完整的DEMO工程

目前有一个简单 DEMO 工程: [https://github.com/alipay/sofa-boot/tree/master/sofaboot-samples/sofaboot-sample-with-isle](https://github.com/alipay/sofa-boot/tree/master/sofaboot-samples/sofaboot-sample-with-isle)，更完整的 DEMO 工程还在准备中。

**Comment by Alfred-it** [comment]
好的，Thanks
