### ISSUE TITLE
Spring-Parent怎么没有效果

### ISSUE THREAD

**Issue by nolan4954** [alipay/sofa-boot#163]
比如我的工程里包含，consumer, provider, run三个module，各有自己的 sofa-module.properties，通过看sofa-default日志,这3个模块都install成功了。**问题是，为什么我在consumer的sofa-module.properties文件中配置了Spring-Parent＝run，在run模块中还是@Resource不到consumer的bean？？？**
依赖的是最新版本2.4.3

**Comment by QilongZhang** [comment]
@nolan4954   麻烦把工程上传到github，贴个link

**Comment by QilongZhang** [comment]
@nolan4954  有没有其他报错信息？ 目前内部测试，@resource 是生效的，可以查看被打 @resource 标的bean是否成功生成。

**Comment by nolan4954** [comment]
可以关掉这个了。
首先是我理解错误，A模块Spring-Parent为B模块，那么只能是A模块看到B模块的bean，而我原来的理解正好是相反的；
其次是#168](https://github.com/alipay/sofa-boot/issues/168)会解决同一个上下文中无法识别注解形式的bean

**Comment by QilongZhang** [comment]
@nolan4954 好的~
