### ISSUE TITLE
关于SOFABoot的实践效率问题

### ISSUE THREAD

**Issue by panlw** [alipay/sofa-boot#164]
请问，SOFABoot在使用类隔离SOFAArk的情况下，Spring Boot DevTool 还能正常使用吗？如果不行的话，有什么比较好替代措施或者比较好的开发实践？

**Comment by QilongZhang** [comment]
@panlw  在使用类隔离 SOFAArk 情况下，DevTools 的热更新不能正常使用。SOFAArk 对 DevTools 的适配在规划内。你这边是在使用 SOFABoot 的类隔离能力吗？

**Comment by panlw** [comment]
目前还没有，不过对SOFAArk的特性比较感兴趣，所以想了解一下`类隔离`关于工程实践方面的情况。

**Comment by QilongZhang** [comment]
@panlw  嗯，可以试用熟悉下，如果有较强的使用需求，我们会提高优先级支持，也更欢迎PR共建。

**Comment by panlw** [comment]
@QilongZhang 3Q!
