### ISSUE TITLE
sofa应用已经发布成功的服务，有链接可以直观的看到吗

### ISSUE THREAD

**Issue by Alfred-it** [alipay/sofa-boot#165]

**Comment by QilongZhang** [comment]
现在还没有，`sofaBootComponentHealthCheckInfo` 目前只会展示整体的健康检查状态，还没有提供详细的服务情况，后续会提供详情展示。更欢迎直接给我们 PR ~

**Comment by Alfred-it** [comment]
ok

**Comment by khotyn** [comment]
@leizhiyuan 可以考虑在下个版本中在 Lookout 中把服务相关的信息给暴露出来。

**Comment by leizhiyuan** [comment]
好的，现在在健康检查中的页面有这个信息，下个版本我们都 lookout 中也上报一下

**Comment by leizhiyuan** [comment]
see https://github.com/alipay/sofa-rpc/issues/242
