### ISSUE TITLE
sofa应用发布，通过什么链接和信息来判断服务应用发布成功

### ISSUE THREAD

**Issue by Alfred-it** [alipay/sofa-boot#166]
curl  http://localhost:8080/health/readiness  这个
{
  status: "UP",
  sofaBootComponentHealthCheckInfo: {
    status: "UP"
  },
  springContextHealthCheckInfo: {
    status: "UP"
  },
  DiskSpace: {
    status: "UP",
    total: 250140434432,
    free: 22845308928,
    threshold: 10485760
  }
}

这几个status都要检查吗？  他们表示什么意思

**Comment by QilongZhang** [comment]
`health/readiness` 表示应用启动期的健康检查，如果健康检查成功，应用对外发布的RPC服务才会暴露。
`sofaBootComponentHealthCheckInfo` 表示的是应用内部发布的服务是否正常。
`springContextHealthCheckInfo` 表示的是 Spring 上下文是否刷新成功。
`DiskSpace` 是 Spring Boot 原生的。

健康检查会检查1、`HealthIndicator` 所有的实现，包括Spring Boot 原生的。 2、SOFABoot 框架自身定义的健康检查扩展。 只有所有健康检查成功，应用才会健康检查通过。

**Comment by Alfred-it** [comment]
thanks
