### ISSUE TITLE
核心应用是不需要web模块的，只是提供sofa-rpc服务，那么其他非sofa的web应用 如何与sofa核心应用通信呢？ 

### ISSUE THREAD

**Issue by Alfred-it** [alipay/sofa-boot#167]
SOFABoot 模块一般用于封装对外发布服务接口的具体实现，属于业务层，Controller 属于展现层内容，我们不建议也不支持在 SOFABoot 模块中定义 Controller 组件，Controller 组件相关定义建议直接放在 Root Application Context。

我将核心应用使用sofa的方式提供rpc服务；非核心应用使用springboot的方式启动，那么springboot的工程如何调用sofa的rpc服务？ 
有什么好的方式推荐

**Comment by Alfred-it** [comment]
或者做成一个应用，web模块 使用普通的maven模块，其他模块做成sofa模块？

**Comment by CharlesSong** [comment]
@Alfred-it web模块使用普通的maven模块，没法调用sofa模块吧。最终还是得是sofa模块吧

**Comment by QilongZhang** [comment]
@CharlesSong  可以调用的. SOFA 模块只是会单独成为一个 Spring 上下文。普通的 maven 模块，也可以使用 sofa:service/sofa:reference 标签。

**Comment by caojie09** [comment]
@CharlesSong 并不是只有 SOFABoot 模块才能调用  SOFABoot 模块，可以参考下 2.4.x 分支的 [sofaboot-sample-with-isle](https://github.com/alipay/sofa-boot/tree/2.4.x/sofaboot-samples/sofaboot-sample-with-isle)，里面包含 Controller 组件。
