### ISSUE TITLE
Change Version 2.4.4.SNAPSHOT to 2.4.4

### ISSUE THREAD

**Issue by guanchao-yang** [alipay/sofa-boot#171]
## Describe

Current SOFABoot version is `2.4.4.SNAPSHOT`

## Expected 

SOFABoot version  `2.4.4` for release

**Comment by khotyn** [comment]
2.4.4 是不是等一等，把 @QilongZhang 这边一个日志以及 Ark Plugin 的问题一起修一下，再发布？

**Comment by straybirdzls** [comment]
@khotyn 这个上午 @guanchao-yang 已经发布了

**Comment by QilongZhang** [comment]
@khotyn  2.4.4 已经发布了。Ark Plugin 那个问题已经优化了 见 https://github.com/alipay/sofa-ark/issues/69 ， 和 SOFABoot 无关。 日志和若杉、玄北讨论了下有两种解决方案：
+ 在 ark starter 中设置系统属性
+ 管控sofa-common-tools

**Comment by khotyn** [comment]
@QilongZhang 这个意思是 Ark Plugin 在 2.4.4 中已经解决了么？只是在 2.4.4-SNAPSHOT 中还有问题吗？

**Comment by QilongZhang** [comment]
@khotyn  2.4.4 还有这个问题。需要 SOFARPC 使用 SOFAArk 0.4.0 优化后打包方式重新打个包， SOFAArk 0.4.0 计划是跟随 [2.5.0 发布](https://github.com/alipay/sofa-boot/releases) ，我打算拉个 SOFARPC 分支打个新的插件包。
