### ISSUE TITLE
错误提示不友好

### ISSUE THREAD

**Issue by zhengjianglong915** [alipay/sofa-boot#179]
最近开始学习 springboot 的demo,  使用模块化开发时发现在使用上的一个小细节，希望你们可以优化下提高用户体验。 （该细节不影响正常功能）

具体问题是：
     当某个模块sofa-module.properties 文件的 Require-Module 配置错误时，错误提示是：

```
Caused by: com.alipay.sofa.isle.deployment.DeploymentException: Some SOFABoot module could not be install because of module dependency problem.
```

这个错误能看出是配置依赖的错误，但是很难定位是哪个配置文件的错误。 这边如果能加个细节，提示哪个依赖错误，那就很赞了。  可以方便快速定位问题。 

新手的拙见！

**Comment by QilongZhang** [comment]
@zhengjianglong915  嗯，非常好的反馈，配置错误信息是需要更详细的说明。我们会改进，如果有兴趣 PR就更好哈。

**Comment by caojie09** [comment]
这里的确可以改进下，我们把详细的报错信息打印在了框架目录: [相关代码](https://github.com/alipay/sofa-boot/blob/v2.4.4/isle-sofa-boot-starter/src/main/java/com/alipay/sofa/isle/stage/SpringContextInstallStage.java#L116)，抛异常的时候只是简单说明了依赖错误，但是却没有说明是哪个模块依赖错误，不利于排查问题，@zhengjianglong915 有兴趣提个pr帮助改进下嚒~

**Comment by zhengjianglong915** [comment]
@caojie09 @QilongZhang  好的，等我把这些了解差不多了，尝试PR下。

**Comment by QilongZhang** [comment]
@zhengjianglong915 了解的怎么样了呢？

**Comment by zhengjianglong915** [comment]
@QilongZhang 最近在看 SOFARPC 和 SOFATrace的源码， 这个问题暂时还没跟进。
