### ISSUE TITLE
健康检查的未来发展计划

### ISSUE THREAD

**Issue by darren-wang** [alipay/sofa-boot#183]
刚拉了健康检查starter的代码，看到master分支上有很多类被声明为`@Deprecated`，比如`HealthChecker`接口，而注释则说更建议使用Spring提供的`HealthIndicator`接口，相关文档上面依然是以旧的接口和类为准的，请问如果后续基于SOFA健康检查想进行扩展时，`HealthChecker`接口都替换成了Spring原生的`HealthIndicator`接口，那么SOFA健康检查的特性又是什么？

**Comment by QilongZhang** [comment]
首先非常感谢提问~

> 先回答最后一个问题：SOFA健康检查的特性是什么？

区别于 Spring Boot 的健康检查，SOFABoot 将健康检查分为两类：

+ Readiness Health Check
+ Liveness Health Check

Readiness Health Check 可以理解为启动期健康检查，即在应用启动期间，对各中间件组件（例如RPC）进行健康状态的检查，比如是否成功连接注册中心、是否正常引用到其他应用发布的服务等等；如果健康检查失败，则应用不会对外暴露服务，如此即可避免上游流量进入不健康的机器。另外，SOFABoot 也提供了给应用扩展的健康检查接口，做一些业务相关的定制检查。

Liveness Health Check 表示的是在应用运行期，检查应用是否处于健康状态，这类检查和 Spring Boot 提供的类似，在蚂蚁金服内部，会定时检查线上机器是否健康，如果健康检查失败，则会下线机器，避免业务处理失败。

以上是 SOFABoot 和 Spring Boot 健康检查的主要区别，即 SOFABoot 在 Spring Boot 提供的 Liveness Health Check 基础之上，提供了 Readiness Health Check.

> 再回答前一个问题：SOFA 健康检查的发展规划是啥？

应用的健康检查在蚂蚁金服有漫长的历史，也因为功能定位明确，已经是很稳定的一个功能组件。如你所说，在 SOFABoot 2.5.0-SNAPSHOT 版本中，我们只是对健康检查进行了代码重构，原因如下：
+ SOFA 健康检查在蚂蚁内部历史悠久，我们在纯 Spring 框架内也支持应用健康检查这一能力，你看到的 @Deprecated 注释的类是我们基于纯 Spring 框架的实现方式。
+ SOFABoot 是基于 Spring Boot 扩展的开发框架，为了使代码更加的 Spring Boot Style，我们希望使用原生的健康检查扩展接口，但并不影响 SOFABoot 健康检查本身的功能定位。

> 最后一个问题：文档和代码的不同步

SOFABoot 2.5.0-SNAPSHOT 还没有正式发布，目前我们的官网还没有支持按版本组织文档，导致现在代码和文档没有保持同步，抱歉。针对文档问题，我们会尽量提供一个好的解决方式。

最后感谢关注和反馈，非常不错一个问题，期待后续你更多的参与。
