### ISSUE TITLE
optimize SofaRuntimeConfigurationProperties

### ISSUE THREAD

**Issue by ScienJus** [alipay/sofa-boot#184]
1. Remove the useless fields `skipJvmReferenceHealthCheck` and `disableJvmFirst`.
2. add `spring-boot-configuration-processor` to `runtime-sofa-boot-starter` for generating metadata of SofaRuntimeConfigurationProperties.

**Comment by QilongZhang** [comment]
thanks for your proposal， welcome pr for this optimization~
