### ISSUE TITLE
runtime的shutDown逻辑疑问

### ISSUE THREAD

**Issue by arebya** [alipay/sofa-boot#188]
看到SofaRuntimeManager中的shutdown逻辑如下：
`public void shutdown() throws ServiceRuntimeException {
        try {
            for (ApplicationShutdownCallback callback : applicationShutdownCallbacks) {
                callback.shutdown();
            }
            if (componentManager != null) {
                componentManager.shutdown();
            }
            clear();
        } catch (Throwable throwable) {
            throw new ServiceRuntimeException(throwable);
        }
    }
`
有几个疑问：
1、applicationShutDownCallback和component的shutdown执行顺序是如何考虑的？
2、这种方式能实现服务的优雅关闭吗？如果不能，有另外的支持方案吗？
3、clear方法没有清理runtimeHealthCheckers

**Comment by QilongZhang** [comment]
@arebya  感谢反馈，问题比较细节，依次回答你的三个问题。
> applicationShutDownCallback和component的shutdown执行顺序是如何考虑的？

`ApplicationShutDownCallback` 在设计上不是一个推荐给应用扩展的接口，只是在内部使用，虽然代码中是一个 list 列表，只是为了后续可能的扩展，目前内部只有一个实现 `CloseApplicationContextCallBack`，关掉应用的上下文。**这个接口是为了支持sofa ark进行应用的动态安装和卸载**，可以参考 [sofa-jarslink](https://github.com/alipay/sofa-jarslink) 和 [sofa-ark](https://github.com/alipay/sofa-ark) 。 如果应用本身想实现callback 调用，推荐使用 Spring Boot 标准的`ApplicationListener` 监听上下文关闭事件，配合 `Ordered` 和 `PriorityOrdered` 使用天然支持顺序。component 的关闭，我们目前是放在最后处理。

> 这种方式能实现服务的优雅关闭吗？如果不能，有另外的支持方案吗？

这里做的只是把component对象注销，包括如果是RPC Component会通知配置中心摘除地址。是否会影响当前正在处理的流量以及因为配置中心时间差，RPC客户端没有及时更新地址列表导致流量的进入，需要依赖RPC服务端的具体实现，这个可以在 [sofa-rpc](https://github.com/alipay/sofa-jarslink) 提问

> clear方法没有清理runtimeHealthCheckers

为了保持代码统一，后续会置空，本质上其实不会影响。
