### ISSUE TITLE
Sofa-boot 调用 Ark plugin 时传一个普通三方 jar 包中的类对象作为参数，又会产生类冲突

### ISSUE THREAD

**Issue by guozhaotong** [alipay/sofa-boot#191]
目前遇到这样一个问题。如果：
- 有一个普通 jar 包 packageA ，packageA 中有一个类 ClassA ；
- Sofa-boot 依赖于普通 jar 包 packageA；
- Ark-plugin 也依赖于普通 jar 包 packageA；
- Sofa-boot 调用 Ark-plugin 中函数的时候，传了一个 ClassA 对象作为参数；

那么，Sofa-boot 和 Ark-plugin 所依赖的 jar 包 packageA 中的类 ClassA 又冲突了。
请问这种情况有办法避免吗？

**Comment by QilongZhang** [comment]
没有太理解，能否发一个demo

**Comment by guozhaotong** [comment]
https://github.com/guozhaotong/sofa-boot-ark-conflict-demo/tree/spring-boot
您好！我在上面链接中上传了一个demo。具体的问题都写在readme中了。
