### ISSUE TITLE
有没有官方讨论群或者钉钉群或者gitter？

### ISSUE THREAD

**Issue by CharlesSong** [alipay/sofa-boot#206]
有没有官方讨论群或者钉钉群或者gitter？

**Comment by QilongZhang** [comment]
![image](https://user-images.githubusercontent.com/8833026/44965786-28c20c00-af6a-11e8-8dcd-ab49fa0d503f.png)

**Comment by QilongZhang** [comment]
@CharlesSong 扫下上面的二维码

**Comment by CharlesSong** [comment]
@QilongZhang 已加，感谢。
