### ISSUE TITLE
与mybits整合问题时  

### ISSUE THREAD

**Issue by zhangqiang1116** [alipay/sofa-boot#236]
与mybits整合问题时  怎么以spring  boo自动配置方式配置Mybits的相关配置  数据库dal单独module

**Comment by QilongZhang** [comment]
[用例链接](https://github.com/alipay/sofa-boot/tree/master/sofaboot-samples/sofaboot-sample-standard) 演示的是在 sofa module 中配置数据库，但是没有和mybatis整合，你可以参考下。

sofa module 只能以xml的方式配置，如果mybatis使用spring boot自动配置形式可能会存在问题，麻烦提供下你的demo。

**Comment by zhangqiang1116** [comment]
意思是我单独的数据dal的Module  我必须xml配置相关以及dataSource？  不能以自动配置的方式吗
demon地址：https://github.com/zhangqiang1116/ipay-upsm.git

**Comment by zhangqiang1116** [comment]
> [用例链接](https://github.com/alipay/sofa-boot/tree/master/sofaboot-samples/sofaboot-sample-standard) 演示的是在 sofa module 中配置数据库，但是没有和mybatis整合，你可以参考下。
> 
> sofa module 只能以xml的方式配置，如果mybatis使用spring boot自动配置形式可能会存在问题，麻烦提供下你的demo。

意思是我单独的数据dal的Module 我必须xml配置相关以及dataSource？ 不能以自动配置的方式吗
demon地址：https://github.com/zhangqiang1116/ipay-upsm.git

**Comment by QilongZhang** [comment]
@zhangqiang1116  我这边运行你的demo是ok的，demo的使用方式理论是可以的，请问你那边遇到了什么问题吗？

**Comment by zhangqiang1116** [comment]
> @zhangqiang1116 我这边运行你的demo是ok的，demo的使用方式理论是可以的，请问你那边遇到了什么问题吗？

非常感谢  这边配置的问题  按照文档是OK的
