### ISSUE TITLE
JVM服务之间调用，如何进行全局异常处理。

### ISSUE THREAD

**Issue by ihanfeng** [alipay/sofa-boot#241]
A-provider调用B-provider的服务接口，B业务层抛出自定义的BusinessException异常应该如何进行拦截处理。不然默认都抛出500错误。
`try {
    // 业务处理异常        
} catch (WxErrorException e) {
    throw new BusinessException(WechatErrorEnum.WECHAT_ERROR_10002);
}`

原来没有使用sofaboot模块化功能，使用@ControllerAdvice可以完美处理，现在JVM之间调用没有经过controller就没法全局处理异常。

有什么办法把B的业务异常抛给调用方，由调用方进行统一处理？

**Comment by QilongZhang** [comment]
@ihanfeng JVM 调用异常抛出的依然是自定义的BusinessException，不需要做特殊处理。如果有问题，请提供相应的复现demo.
