### ISSUE TITLE
sofa boot模块隔离的问题

### ISSUE THREAD

**Issue by zhangqiang1116** [alipay/sofa-boot#254]
我利用sofaBoot 做了模块隔离，有这些模块：common-util,biz-service,core-service,sofa-start
现在搭建框架时有两个疑惑：
1.自定义用log4j2做日志框架,想在sofa-start这个启动模块中做系统所有的配置，包括这个log4j2，并且在common-util这个模块中引入log4j2,让其他模块导入common-util做日志打印。这个可以在sofa-start这个启动模块中做全局的log4j2日志打印配置吗?

2.用了rocketMq，想在sofa-start启动模块中做MQ的相关配置，在biz-service模块中做消息的监听与消息接受的业务处理，在core-service中做MQ消息发送，可以做到在启动模块做全局的配置吗？

**Comment by zhangqiang1116** [comment]
> @zhangqiang1116 回答你的两个问题：
> 
> * 应用的日志配置在多个模块之间是相互共用的，模块隔离不等同类隔离，应用的日志配置是共用的。
> * rocketMq starter 会在启动模块初始化配置，可以做到全局配置。
> 
> 如果有问题，可以提供复现 Demo, 我们会跟进。

模块之间不是相互隔离的吗  我在启动模块中配置MQ的配置，然后再biz-service中pom.xml中引入MQ的包，不需要在配置吗？

**Comment by QilongZhang** [comment]
@zhangqiang1116  你说的在启动模块的MQ 配置，我理解是在application.properties 中的？ 默认情况下，application.properties 的配置是所有sofa isle 共享的。

**Comment by zhangqiang1116** [comment]
> @zhangqiang1116 你说的在启动模块的MQ 配置，我理解是在application.properties 中的？ 默认情况下，application.properties 的配置是所有sofa isle 共享的。

对是在application.properties中配置MQ，  但消息的处理接受和发送在另外两个模块，这样我在这两个模块中pom.xml引入MQ过后  ，由于spring 环境是隔离的，难道不再次需要配置相关信息吗 ？

**Comment by khotyn** [comment]
@zhangqiang1116 你引入的应该是 RocketMQ 的 Spring Boot 的 Starter？如果是引入的 Starter，Starter  应该是作为一个 Root Application Context 被所有的模块所共享吧。

**Comment by QilongZhang** [comment]
> > @zhangqiang1116 你说的在启动模块的MQ 配置，我理解是在application.properties 中的？ 默认情况下，application.properties 的配置是所有sofa isle 共享的。
> 
> 对是在application.properties中配置MQ， 但消息的处理接受和发送在另外两个模块，这样我在这两个模块中pom.xml引入MQ过后 ，由于spring 环境是隔离的，难道不再次需要配置相关信息吗 ？

application.properties 中的配置是所有模块共享的，不需要再次配置相关信息。

**Comment by zhangqiang1116** [comment]
> @zhangqiang1116 你引入的应该是 RocketMQ 的 Spring Boot 的 Starter？如果是引入的 Starter，Starter 应该是作为一个 Root Application Context 被所有的模块所共享吧。

意思是 在Root Application Context中Starter配置了相关信息过后，其他子模块需要用MQ直接maven引入这个start,就不用再再次配置了吗

**Comment by khotyn** [comment]
@zhangqiang1116 是的，你可以试一下，如果有问题的话，可以在这个 ISSUE 上贴出来。
