### ISSUE TITLE
关于类隔离的问题请教g

### ISSUE THREAD

**Issue by iyayu** [alipay/sofa-boot#256]
1. 是使用 Ark Plugin 插件来实现了类隔离?
2. 我的模块中引入的第三方包与其它模块发生了冲突这个时候我需要将我的模块写成一个插件吗？
3. 只有导出的类才会独立的 ClassLoader 加载？还是说我插件中的所有类(包括第三方包)都会由独立的 ClassLoader 加载.

麻烦解答一下谢谢🙏

**Comment by QilongZhang** [comment]
@iyayu  插件中所有的类都会有独立的 ClassLoader 加载。 导出的类能能够被其他导入该类的插件resolved，默认情况下，插件的导出类都能够被 Biz resolved。

**Comment by iyayu** [comment]
谢谢:) 我想问一下 api 在哪

**Comment by iyayu** [comment]
> @iyayu 插件中所有的类都会有独立的 ClassLoader 加载。 导出的类能能够被其他导入该类的插件resolved，默认情况下，插件的导出类都能够被 Biz resolved。

谢谢:) 我想问一下 api 在哪

**Comment by iyayu** [comment]
谢谢:) 我想问一下 api 在哪

**Comment by QilongZhang** [comment]
不用 api ， 直接使用 new 就可以了。
