### ISSUE TITLE
RPC引用支持 placeholder

### ISSUE THREAD

**Issue by chpengzh** [alipay/sofa-boot#260]
问题内容详见 [alipay/sofa-rpc-boot-projects](https://github.com/alipay/sofa-rpc-boot-projects/issues/109)

感谢 @QilongZhang @JervyShi @ScienJus 提出的修改建议，后续内容将在这个Issue下更新。

**Comment by ScienJus** [comment]
顺便提供参考下 spring-cloud-openfeign 的实现：

https://github.com/spring-cloud/spring-cloud-openfeign/blob/master/spring-cloud-openfeign-core/src/main/java/org/springframework/cloud/openfeign/FeignClientsRegistrar.java#L252-L257

其实一般逻辑大概就是判断 val 有没有可能是一个 placeholder，例如 `startwiths('${') and endwiths('}')` 之类的做法，如果是的话就用 `Environment#resolvePlaceholders` 获取即可，这个方法会帮助你解决不同来源（sys、env、yaml）以及优先级的问题。

have fun!
