### ISSUE TITLE
目前有对接 Prometheus 的 exporter 吗？

### ISSUE THREAD

**Issue by wdxxs2z** [alipay/sofa-boot#272]
针对社区的发展进度，目前有提供Prometheus operator的计划吗，如果要自己扩展的话，需要从哪里扩展啊？

**Comment by khotyn** [comment]
@wdxxs2z 你说的是 Prometheus 的 K8s operator 还是啥？

**Comment by wdxxs2z** [comment]
Prometheus 的 K8s operator，我在lookout里面看到了一部分功能

**Comment by khotyn** [comment]
@wdxxs2z Operator 是用来运维 Prometheus 的，我理解 SOFABoot 应该不用额外做什么对接。

**Comment by wdxxs2z** [comment]
@khotyn sorry,当时写错了，不是 operator，是exporter的支持，我看到了lookout有这部分的说明

**Comment by khotyn** [comment]
@wdxxs2z 是的，Lookout 是支持 Prometheus 的。
