### ISSUE TITLE
卸载Biz包时使用容器类加载器导致的问题

### ISSUE THREAD

**Issue by iteaj** [alipay/sofa-boot#273]
在卸载Biz包的时候， 类加载器使用的是ContainerClassLoader， 导致在卸载的时候报错
比如：在执行EventHandler的卸载事件时引用到了SofaFramework.导致的找不到类， 因为SofaFramework是由Sofa-rumtime插件提供的， 如果用ContainerClassLoader加载会找不到该类

**Comment by QilongZhang** [comment]
请问 SOFABoot 使用的是哪个版本？

**Comment by iteaj** [comment]
> 请问 SOFABoot 使用的是哪个版本？

3.0版本

**Comment by QilongZhang** [comment]
@iteaj  我这边装载卸载多biz时，运行正常。[sofa-jarslink demo](https://github.com/alipay/sofa-jarslink/tree/master/sofa-jarslink-samples/biz-jvm-invocation-sample)

**Comment by iteaj** [comment]
> @iteaj 我这边装载卸载多biz时，运行正常。[sofa-jarslink demo](https://github.com/alipay/sofa-jarslink/tree/master/sofa-jarslink-samples/biz-jvm-invocation-sample)
我的是在自己写的插件里面的事件处理器报的错, 因为引用到了SofaFramework
`public class WebEventHandler implements EventHandler {

    /**
     * 此事件处理器必须在
     * {@link com.alipay.sofa.runtime.integration.service.SofaEventHandler}
     * 之后被调用
     */
    private static int SOFA_EVENT_HANDLER_AFTER = DEFAULT_PRECEDENCE + 10;

    @Override
    public void handleEvent(ArkEvent event) {

        //如果是卸载Biz包事件
        if(event instanceof BizEvent && Constants
                .BIZ_EVENT_TOPIC_UNINSTALL.equals(event.getTopic())) {
            SofaFramework.getRuntimeSet().stream().filter((a)-> a.getAppClassLoader()==((BizEvent) event)
                    .getBiz().getBizClassLoader());
//            ((BizEvent) event).getBiz().getMainClass()
        }
    }

    @Override
    public int getPriority() {
        return SOFA_EVENT_HANDLER_AFTER;
    }
}`

**Comment by QilongZhang** [comment]
插件是否配置了导入类 SofaFramework ？ 
可以方便提供问题的复现demo 么
