### ISSUE TITLE
模块化类隔离BeanId冲突问题

### ISSUE THREAD

**Issue by cxntsh** [alipay/sofa-boot#287]
Consumer 模块的 service bean：

`
@Service
public class JvmServiceConsumer {
	@SofaReference(uniqueId = "annotationImpl")
	private SampleJvmService sampleJvmServiceByFieldAnnotation;
}
`
Provider 模块的 service bean：

`@Service
public class JvmServiceConsumer {
	public void index() {
		System.out.println("HelloWorld");
	}
}`

或者 本模块的 另外一个 service 设置 beanId 为 jvmServiceConsumer

`
@Service("jvmServiceConsumer")
@SofaService(uniqueId = "annotationImpl")
public class SampleJvmServiceAnnotationImpl implements SampleJvmService {
	@Override
	public String message() {
		String message = "Hello, jvm service annotation implementation.";
		System.out.println(message);
		return message;
	}
}
`

SpringBoot application 启动的时候 赤裸裸的 beanId 冲突

`Caused by: org.springframework.context.annotation.ConflictingBeanDefinitionException: Annotation-specified bean name 'jvmServiceConsumer' `

何解？  每个模块都配置了 Module-Name，参考了 git 开源的 demo

**Comment by QilongZhang** [comment]
方便请提供下问题复现demo.

**Comment by cxntsh** [comment]
谢谢回复！
GitHub 地址：  https://github.com/cxntsh/itsm-sofaboot.git

**Comment by cxntsh** [comment]
你好，项目地址 我推了一个 hotfix，把扫描包范围缩小到了 root application 范围。
看了一下 SOFA 的源码，基本摸清了，问题已经解决。
SpringApplication run 如果是 web 工程，会初始化一个 AnnotationConfigReactiveWebServerApplicationContext，如果扫描包的路径 包含所有的 类 并且 是基于 @Component扩展 来标注的类，就算你写了 Module-Name（SOFA 判定是不是一个模块，依据：     ModuleName != null 判定），认为这是一个模块（官方资料说可以 类隔离），如果出现类名一致或者beanId写了一致，那么必然会报 BeanId  Confict。（这个时候SofaModuleApplicationContext 还没加载呢）。 其次， SofaModuleApplicationContext 貌似不支持加载 Annotation 的声明方式， jvmService 可以用  Annotation 的方式声明暴露，但是 类的注册 一定要在 META-INF 下的 xml 文件中配置 <bean> ，
这里配置的 bean id 在不同的模块【重复】才不会报 bean conflict！ 
个人理解（希望可以帮到大家填坑）。
希望 SOFA 的 SofaModuleApplicationContext  以后可以支持 @Component扩展  来加载 bean，而不需要去配置 xml。

**Comment by QilongZhang** [comment]
@cxntsh 
使用 SOFABoot 模块隔离，配置 ComponentScan 需要特别注意下：
+ 即使存在多个 sofa 模块，component scan 也是全应用扫描

另外一个看你描述说 `认为这是一个模块（官方资料说可以 类隔离）`，其实不然，模块只是 spring  上下文隔离而不是类隔离

其次 `SofaModuleApplicationContext 貌似不支持加载 Annotation 的声明方式`，其实注解和服务都是支持注解的，只是现在配一个xml引导，你可以只在一个xml中，配置一个 ComponentScan 将该模块所有的bean 都囊括进来尽快，另外我们现在正在优化哈，会提供一个特殊的注解，替换xml作为模块上下文的入口。

**Comment by cxntsh** [comment]
了解了，谢谢

**Comment by TomorJM** [comment]
> @cxntsh
> 使用 SOFABoot 模块隔离，配置 ComponentScan 需要特别注意下：
> 
> * 即使存在多个 sofa 模块，component scan 也是全应用扫描
> 
> 另外一个看你描述说 `认为这是一个模块（官方资料说可以 类隔离）`，其实不然，模块只是 spring 上下文隔离而不是类隔离
> 
> 其次 `SofaModuleApplicationContext 貌似不支持加载 Annotation 的声明方式`，其实注解和服务都是支持注解的，只是现在配一个xml引导，你可以只在一个xml中，配置一个 ComponentScan 将该模块所有的bean 都囊括进来尽快，另外我们现在正在优化哈，会提供一个特殊的注解，替换xml作为模块上下文的入口。

请问现在模块内支持声明bean的注解么(类似于@Component), 现在在模块内使用一个普通bean都需要定义声明在xml文件里, 感觉使用上很麻烦~

**Comment by QilongZhang** [comment]
> > @cxntsh
> > 使用 SOFABoot 模块隔离，配置 ComponentScan 需要特别注意下：
> > 
> > * 即使存在多个 sofa 模块，component scan 也是全应用扫描
> > 
> > 另外一个看你描述说 `认为这是一个模块（官方资料说可以 类隔离）`，其实不然，模块只是 spring 上下文隔离而不是类隔离
> > 其次 `SofaModuleApplicationContext 貌似不支持加载 Annotation 的声明方式`，其实注解和服务都是支持注解的，只是现在配一个xml引导，你可以只在一个xml中，配置一个 ComponentScan 将该模块所有的bean 都囊括进来尽快，另外我们现在正在优化哈，会提供一个特殊的注解，替换xml作为模块上下文的入口。
> 
> 请问现在模块内支持声明bean的注解么(类似于@component), 现在在模块内使用一个普通bean都需要定义声明在xml文件里, 感觉使用上很麻烦~

嗯，xml 能控制扫描的bean在单独的模块，理论上可以提供特殊的 autoconfigure 注解解决这个问题，如果有更好的方案，可以给我们贡献 PR ~
