### ISSUE TITLE
关于sofaboot的模块化

### ISSUE THREAD

**Issue by reenWYJ** [alipay/sofa-boot#292]
不太理解为什么要使用spring上下文隔离的模块

因为之前使用以package为粒度的隔离很长时间并没有发现问题

**Comment by khotyn** [comment]
可以参考下这篇文章：https://mp.weixin.qq.com/s/M3bNIDNiFQBLs9QGpwVLsw

**Comment by reenWYJ** [comment]
@khotyn 谢谢!
