### ISSUE TITLE
sofaboot3.1 启动报错,Failed to resolve @SofaService on @Bean-method({}) in {}

### ISSUE THREAD

**Issue by shen0834** [alipay/sofa-boot#305]
```java
private void generateSofaServiceDefinitionOnMethod(String beanId,
                                                       AnnotatedBeanDefinition beanDefinition,
                                                       ConfigurableListableBeanFactory beanFactory) {
        Class<?> returnType;
        Class<?> declaringClass;
        Method method = null;

        MethodMetadata methodMetadata = beanDefinition.getFactoryMethodMetadata();
        try {
            returnType = ClassUtils.forName(methodMetadata.getReturnTypeName(), null);
            declaringClass = ClassUtils.forName(methodMetadata.getDeclaringClassName(), null);
            for (Method m : declaringClass.getDeclaredMethods()) {

                Bean bean = m.getAnnotation(Bean.class);
                Set<String> beanNames = Stream.of(m.getName()).collect(Collectors.toSet());
                if (bean != null) {
                    beanNames.addAll(Arrays.asList(bean.name()));
                    beanNames.addAll(Arrays.asList(bean.value()));
                }
                if (!beanNames.contains(beanId)) {
                    continue;
                }
                if (method != null) {
                    throw new IllegalStateException("multi @Bean-method with same name in "
                                                    + declaringClass.getCanonicalName());
                }
                method = m;
            }
        } catch (Throwable throwable) {
            SofaLogger.error(throwable, "Failed to resolve @SofaService on @Bean-method({}) in {}",
                beanId, methodMetadata.getDeclaringClassName());
            throw new FatalBeanException("Failed to resolve @SofaService on method", throwable);
        }

        if (method != null) {
            SofaService sofaServiceAnnotation = method.getAnnotation(SofaService.class);
            if (sofaServiceAnnotation == null) {
                sofaServiceAnnotation = returnType.getAnnotation(SofaService.class);
            }
            generateSofaServiceDefinition(beanId, sofaServiceAnnotation, returnType,
                beanDefinition, beanFactory);
            generateSofaReferenceDefinition(beanId, method, beanFactory);
        }
    }
```

在引入了

```xml
         <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-amqp</artifactId>
        </dependency>
```

在解析`org.springframework.boot.autoconfigure.amqp.RabbitAnnotationDrivenConfiguration`这个类时,`generateSofaServiceDefinitionOnMethod`会在解析`RabbitAnnotationDrivenConfiguration`中的 `@Bean `类时   throw new IllegalStateException("multi @Bean-method with same name in "的错误,看了下业务逻辑,除非我不使用AMQP-STARTER去除自动装载,要不一定会报错启动不了项目

**Comment by ScienJus** [comment]
这个似乎是因为静态扫描遇到了多个同名 @Bean 配置了不同的 @Conditional 的情况。这里不知道能否直接通过 `AnnotatedTypeMetadata` 拿到注解信息。

PS：不是 sofa 维护者，只是补充一个参考。

**Comment by khotyn** [comment]
@ujjboy

**Comment by ScienJus** [comment]
@QilongZhang 请教一下，`@SofaReference` 作为参数注入的这个功能，有尝试过使用 `AutowireCandidateResolver` 么？

看上去直接在 BeanDefinition 拿到调用方法和参数比较困难（小概率能得到 `StandardMethodMetadata`），用这个实现注入相关的逻辑似乎更简单（在注入时被调用，能拿到方法参数类型和注解，返回值会被注入到方法中），就是不知道实现上是否会有什么坑。

**Comment by QilongZhang** [comment]
@ScienJus 感谢交流，`AutowireCandidateResovler` 没有试过，我研究下呢。 目前 `@SofaReference` 实现注入的逻辑是通过 `com.alipay.sofa.runtime.spring.bean.SofaParameterNameDiscoverer` 这个类扩展实现的，应该是不依赖 `StandardMethodMetadata` 。

**Comment by QilongZhang** [comment]
@ScienJus  `AutowireCandidateResolver`  应该也可以用于解决 @SofaReference 注入，当前的注入方案是通过 `SofaParameterNameDiscoverer ` 这个类，修改参数名称做到的，感谢建议，不考虑其他因素，AutowireCandidateResovler 实现上应该会简单点。

这个 issue 的报错的原因是，在解析 method 上的 SofaService 注解时，根据当前的 BeanDefinition 没有找到合适的手段确定唯一生成该 BeanDefinition 的 Method，请问这块你有什么好的建议。

**Comment by ScienJus** [comment]
Demo 大概是：

```
public class SofaReferenceAutowireCandidateResolver implements AutowireCandidateResolver {

    private ConfigurableApplicationContext applicationContext;

    private AutowireCandidateResolver delegate;

    private SofaRuntimeContext sofaRuntimeContext;

    private BindingConverterFactory bindingConverterFactory;

    private BindingAdapterFactory bindingAdapterFactory;

    public SofaReferenceAutowireCandidateResolver(
            ConfigurableApplicationContext applicationContext, 
            AutowireCandidateResolver delegate, 
            SofaRuntimeContext sofaRuntimeContext, 
            BindingConverterFactory bindingConverterFactory, 
            BindingAdapterFactory bindingAdapterFactory) {
        this.applicationContext = applicationContext;
        this.delegate = delegate;
        this.sofaRuntimeContext = sofaRuntimeContext;
        this.bindingConverterFactory = bindingConverterFactory;
        this.bindingAdapterFactory = bindingAdapterFactory;
    }

    @Override
    public Object getSuggestedValue(DependencyDescriptor descriptor) {
        SofaReference sofaReference = descriptor.getAnnotation(SofaReference.class);
        if (sofaReference == null) {
            return delegate.getSuggestedValue(descriptor);
        }
        // Copy from ReferenceAnnotationBeanPostProcessor
        return createReferenceProxy(sofaReference, descriptor.getDependencyType());
    }
}
```

运行时大概是：

![image](https://user-images.githubusercontent.com/8350653/50325248-a8c2b080-051e-11e9-9d75-622132ab653c.png)

![image](https://user-images.githubusercontent.com/8350653/50325260-b6783600-051e-11e9-91a0-16989e2365c3.png)

不知道能否满足需求以及覆盖到所有情况…

**Comment by QilongZhang** [comment]
@ScienJus  当前的方案使用既有的 BeanDefinition 解析对应的 FactoryMethod，可能不是一个优雅的方案，在这个方案下，解析操作比较复杂，**直觉上应该发生在 ConfigurationClassBeanDefinition  Parser 阶段处理，不知道你怎么看**

`methodMetadata.getAnnotationAttributes(SofaService.class.getName());`  其实尝试过这样拿，但是因为返回结果是一个 Map 结构，并不是一个直接的 @SofaService 注解类型，对于 RPC 服务来讲，属性太多而且存在嵌套注解，解析繁琐。

另外顺便说一下，为什么会使用 BeanDefiniton 的方式.  我觉得 ConfigurationClass 是代码化的配置，和 Spring xml 类似。因此 Spring Boot 在解析 Configuration Class 时，采用 xml 类似的处理，是直接转换成了 BeanDefinition.  之前的 SOFABoot 版本，xml 配置的 SofaService 和  SofaReference 都是解析成具体的 BeanDefinition， 而注解方式并不会生成对应的 BeanDefinition，而是通过 PostProcessor 处理。为了统一模型，尽量希望能够以 BeanDefinition 方式统一处理。

**Comment by QilongZhang** [comment]
> Demo 大概是：
> 
> ```
> public class SofaReferenceAutowireCandidateResolver implements AutowireCandidateResolver {
> 
>     private ConfigurableApplicationContext applicationContext;
> 
>     private AutowireCandidateResolver delegate;
> 
>     private SofaRuntimeContext sofaRuntimeContext;
> 
>     private BindingConverterFactory bindingConverterFactory;
> 
>     private BindingAdapterFactory bindingAdapterFactory;
> 
>     public SofaReferenceAutowireCandidateResolver(
>             ConfigurableApplicationContext applicationContext, 
>             AutowireCandidateResolver delegate, 
>             SofaRuntimeContext sofaRuntimeContext, 
>             BindingConverterFactory bindingConverterFactory, 
>             BindingAdapterFactory bindingAdapterFactory) {
>         this.applicationContext = applicationContext;
>         this.delegate = delegate;
>         this.sofaRuntimeContext = sofaRuntimeContext;
>         this.bindingConverterFactory = bindingConverterFactory;
>         this.bindingAdapterFactory = bindingAdapterFactory;
>     }
> 
>     @Override
>     public Object getSuggestedValue(DependencyDescriptor descriptor) {
>         SofaReference sofaReference = descriptor.getAnnotation(SofaReference.class);
>         if (sofaReference == null) {
>             return delegate.getSuggestedValue(descriptor);
>         }
>         // Copy from ReferenceAnnotationBeanPostProcessor
>         return createReferenceProxy(sofaReference, descriptor.getDependencyType());
>     }
> }
> ```
> 运行时大概是：
> 
> ![image](https://user-images.githubusercontent.com/8350653/50325248-a8c2b080-051e-11e9-9d75-622132ab653c.png)
> 
> ![image](https://user-images.githubusercontent.com/8350653/50325260-b6783600-051e-11e9-91a0-16989e2365c3.png)
> 
> 不知道能否满足需求以及覆盖到所有情况…

感谢 Demo, 用来解决 SofaReference 注入问题是没有问题的。

**Comment by ScienJus** [comment]
赞同在生成 BeanDefinition 时处理差异，在生成 BeanDefinition 之后的逻辑保持统一。方法的 annotation 是不是强类型这是个小事，可以先忽略。但是我觉得这也反映了 spring 在解析 BeanDefinition 时，并不一定真正加载了这个类（这就像是 `@ConditionalOnClass(xxx.class)` 为什么能存在一样？），所以我对能拿到实际方法以及参数并不乐观。

但是注解形式和 xml 形式的最大一个区别是，xml 的 reference 也是用户自己定义的 BeanDefiniton，而注解现在的做法是分析参数并自动生成，所以如果它像 XML 一样应该是这样定义：

```
@Bean("sampleService")
@SofaReference
public SampleService sampleService() {
    return null;
}

@Bean
public SampleService sampleService(@Qualifier("sampleService") SampleService sampleService) {
    return new SampleServiceImpl("test");
}
```

虽然这样很 ugly，但是在 spring 的支持上就天差地别了…

**Comment by QilongZhang** [comment]
>但是我觉得这也反映了 spring 在解析 BeanDefinition 时，并不一定真正加载了这个类（这就像是 @ConditionalOnClass(xxx.class) 为什么能存在一样？），所以我对能拿到实际方法以及参数并不乐观。

这个或许可以借鉴 Spring Boot 在解析 `ConfigurationClassBeanDefinition` 过程，这一步好像已经过滤了条件.

考虑和  XML 对应的话，上面贴的 @SofaReference 注解方式严格意义上是这么定义，需要有下面这一段SofaReference声明
```java
@Bean("refId")
@SofaReference(interface={}, uniqueId={})
public SampleService sampleService() {
    return null;
}
```
只是这段代码其实可以省略，因为在参数上使用 @SofaRefernece 注解，即使不存在上述代码，也不会有歧义，对于用户来讲，这段代码是多余的，写起来也如你所说，有点 ugly，虽然这样给我们支持方案增加了难度：）

**Comment by QilongZhang** [comment]
> 嗯，也就是 spring 官方的 api 能够比较简单的提供两种方式：
> 
> 1. 让用户手动定义 @SofaReference 的 BeanDefinition。优点是不用再去找方法了，缺点是对用户来说，这是一段 ugly 且无意义的代码
> 2. 注入用 AutowireCandidateResolver，spring 保证了所有注入都会调用，且能拿到最重要的参数信息，缺点就是没办法复用已有的 BeanDefinition 逻辑
> 
> 所以其实想在这两种方式找折中，所以有第三种做法：
> 
> 1. 手动从 Configuration 里通过 @Bean/method name 扫描到对应方法，优点是兼顾了上面两个的缺点，缺点是目前没办法识别唯一方法（因为参数信息丢了，方法签名是不完整的）
> 
> 考虑到对用户的使用方式来看，1 基本可以排除，2 和 3 对用户暴露的 API 都是相同的，所以就是尽量能以 3 的方式实现，但是也许 2 能够保底。
> 
> 在真实世界里，通过过滤方法名 + 注解信息是不是也能保证找到唯一方法？虽然 Java 的方法唯一标识是方法名 + 参数，但是对于 Spring 的 BeanDefinition 来说，是不存在所谓的重载的，理论上同 BeanId 方法只可能存在于不同 Conditional 的情况。
> 
> 昨晚一直在啃 `ConfigurationClassBeanDefinition` 在什么场景能解析到原生方法对象（其实也就是我最开始说的 `StandardMethodMetadata `），但是实际运行时发现大部分都不是，我再详细看下原因。

所以采用了第三种方式，担心确实存在同名方法的存在，所以直接抛出错误而不是打印警告日志. 写这块时，发现通过 MethodMetadata 确定不了唯一方法，因此只能通过反射依次判断，不过当时写的判断条件比较简单，如果判断了方法名和返回值，issue 的问题就不会有了，能解决绝大部分问题，毕竟我们通常不会这么写 Bean-Method。

可以一起看下怎么从 `ConfigurationClassBeanDefinition` 这里入手找到好的解决手段。

**Comment by ScienJus** [comment]
> 所以采用了第三种方式，担心确实存在同名方法的存在，所以直接抛出错误而不是打印警告日志. 写这块时，发现通过 MethodMetadata 确定不了唯一方法，因此只能通过反射依次判断，不过当时写的判断条件比较简单，如果判断了方法名和返回值，issue 的问题就不会有了，能解决绝大部分问题，毕竟我们通常不会这么写 Bean-Method。

嗯，真实世界会比理论简单很多，多一些判断条件（返回值、注解）能够让出现的情况逐渐减少到 0，另一个是这里即使有多个方法，但是如果都没有 `@SofaService` 和 `@SofaReference` 就也没必要报错，有的话则肯定是用户自己定义的 Bean，此时报错用户是可以修改的，应该也是可接受的。

有些偏题= = 小 patch 几点优化都做了应该会好很多，我再看看有没有什么办法能根本的找到方法引用…

**Comment by QilongZhang** [comment]
@ScienJus 
看了 Spring Boot 2.1.0.RELEASE 代码，根据方法名和BeanId可以唯一确定对应的方法，关键方法：
`org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader#isOverriddenByExistingDefinition`

```java
		// Is the existing bean definition one that was created from a configuration class?
		// -> allow the current bean method to override, since both are at second-pass level.
		// However, if the bean method is an overloaded case on the same configuration class,
		// preserve the existing bean definition.
		if (existingBeanDef instanceof ConfigurationClassBeanDefinition) {
			ConfigurationClassBeanDefinition ccbd = (ConfigurationClassBeanDefinition) existingBeanDef;
			return ccbd.getMetadata().getClassName().equals(
					beanMethod.getConfigurationClass().getMetadata().getClassName());
		}
```

**Comment by ScienJus** [comment]
@QilongZhang 是这样，但是这个只是在多个 @Bean 都成为 ConfigurationClassBeanDefinition 是否覆盖的情况。

现在的逻辑是扫描静态方法，但是静态方法并不一定会成为 ConfigurationClassBeanDefinition，所以我觉得通过匹配所有的 @Condition 注解的元信息 + 方法名，能够找到一定能加载为 ConfigurationClassBeanDefinition 的 Method，然后其第一顺位就是真正的那个 当前拿到的 BeanDefinition？

**Comment by ScienJus** [comment]
@QilongZhang 感谢说明，这个代码看上去很靠谱（证明官方本身就不靠谱），所以在目前的场景下，赞同模糊查询。

如上文所说，这部分逻辑可以优化为：即使模糊查询依旧无法识别出方法，但是如果这些方法本身就没有 `@SofaReference` 和 `@SofaService` 就可以直接无视，如果有的话，抛出异常并让用户改是比上文代码中官方的做法很 make sense 的方案。

**Comment by shen0834** [comment]
@QilongZhang 这个bug3.1.1依然存在,问一下什么时候能合并到主分支发版,因为我们AMQP也需要随着boot版本升级到2.1.x,请告知下计划,谢谢!
