### ISSUE TITLE
IDE启动app-one与用java -jar 启动方式，后者能正常调用jvm service,前者居然不行？

### ISSUE THREAD

**Issue by grindwheel** [alipay/sofa-boot#327]
![image](https://user-images.githubusercontent.com/10232714/50588513-6786b500-0ebd-11e9-84a9-d070f405ca02.png)
![image](https://user-images.githubusercontent.com/10232714/50589136-62773500-0ec0-11e9-9481-708b2f4cfa1b.png)

**Comment by QilongZhang** [comment]
你是跑哪个demo报错？

**Comment by grindwheel** [comment]
> 你是跑哪个demo报错？

![image](https://user-images.githubusercontent.com/10232714/50621481-1cae8100-0f41-11e9-8ed6-97de38e8a976.png)

**Comment by QilongZhang** [comment]
@grindwheel  
IDEA 启动的时候会默认添加 `-Dspring.application.admin.enabled=true` 导致启动失败，和 java -jar 行文不一致。
https://blog.jetbrains.com/idea/2017/05/intellij-idea-2017-2-eap-run-dashboard-for-spring-boot/

![image](https://user-images.githubusercontent.com/8833026/50673575-bfd2c980-1019-11e9-8877-5f084a158f48.png)

需要通过如下设置：
![image](https://user-images.githubusercontent.com/8833026/50673613-07f1ec00-101a-11e9-9d97-c456c10041ca.png)

sofa ark 需要做一些优化，将启动的应用参数传递给动态安装的 biz, 需要你稍后更新下 ark 包。

**Comment by grindwheel** [comment]
@QilongZhang 
按照你的方式加了这个程序参数后，会出现另一个问题； 现在ark哪个版本可用
![image](https://user-images.githubusercontent.com/10232714/50675730-d33a6080-102a-11e9-96a1-38eaaf719380.png)

**Comment by QilongZhang** [comment]
@grindwheel  嗯，刚看了下， IDEA 在启动参数中额外添加了  -Dspring.liveBeansView.mbeanDomain 参数. 这个参数没法覆盖.  你可以谷歌下如何禁用 IDEA 启动的VM参数，是否兼容这种情况还在考虑中。你在那还是可以通过在代码中设置
```java
System.getProperties().remove("spring.liveBeansView.mbeanDomain");
```
