### ISSUE TITLE
DynamicSpringContextLoader的建议

### ISSUE THREAD

**Issue by hqq2023623** [alipay/sofa-boot#333]
### DynamicSpringContextLoader#loadSpringContext()
``` java
line 59 : SofaModuleProperties sofaModuleProperties = rootApplicationContext
            .getBean(SofaModuleFrameworkConstants.SOFA_MODULE_PROPERTIES_BEAN_ID,
                SofaModuleProperties.class);

……

line 82 :  ctx.setAllowBeanDefinitionOverriding(rootApplicationContext.getBean(
            SofaModuleProperties.class).isAllowBeanDefinitionOverriding());

```
82行这里可以直接使用59行生成的sofaModuleProperties ，修改为：
ctx.setAllowBeanDefinitionOverriding(sofaModuleProperties.isAllowBeanDefinitionOverriding());

因为在spring里面是单例的
![437438bc-4f76-48ad-9569-03c22874da8a](https://user-images.githubusercontent.com/6971152/50805518-bbfeba00-132d-11e9-9aab-869f5a873b37.png)

### Environment
version: 3.1.1
branch:master

**Comment by QilongZhang** [comment]
多谢反馈，我们会在下个小版本优化。

**Comment by straybirdzls** [comment]
@hqq2023623 有没有兴趣提个 PR 优化？

**Comment by hqq2023623** [comment]
@straybirdzls  好的，我会尽快提个PR

**Comment by QilongZhang** [comment]
> @straybirdzls 好的，我会尽快提个PR

可以提到 2.6.0 的迭代

**Comment by straybirdzls** [comment]
@hqq2023623 赞👍 ，2.6.0 迭代在目前的 2.x 分支，期待你的 PR 😊
