### ISSUE TITLE
引入sofa-jarslink-ark-starter 后使用 telnet 显示乱码怎么解决

### ISSUE THREAD

**Issue by Godhuu** [alipay/sofa-boot#342]
![image](https://user-images.githubusercontent.com/23355160/51517734-b2f60880-1e56-11e9-8352-18e33a175f3d.png)

**Comment by QilongZhang** [comment]
中文字符编码问题，SOFAJarslink 功能在 SOFAArk 0.6.0 已经完全集成，参考[发布报告](https://github.com/alipay/sofa-ark/releases/tag/v0.6.0)，在 0.6.0 不会再有这个问题。

参考 [SOFAArk 文档](https://www.sofastack.tech/sofa-boot/docs/sofa-ark-ark-telnet)
