### ISSUE TITLE
Infinitely recursive call in ExtensionBuilder

### ISSUE THREAD

**Issue by hqq2023623** [alipay/sofa-boot#346]
ExtensionBuilder , line 55
``` java
    public static ExtensionBuilder genericExtension(String extensionPoint,
                                                    ApplicationContext applicationContext) {
        return genericExtension(extensionPoint, applicationContext);
    }
```
It's a recursive call without exit and no where else call this method

## Environment 
branch : 2.x

**Comment by straybirdzls** [comment]
@hqq2023623 👍 This method is unused，should be deleted. Do you have interest to create a PR for this?

**Comment by hqq2023623** [comment]
@straybirdzls OK, I will handle this soon

**Comment by straybirdzls** [comment]
@hqq2023623 Great!  You can pr to 2.x branch, looking forward to your pr 😊
