### ISSUE TITLE
Support Spring Boot 2.0

### ISSUE THREAD

**Issue by khotyn** [alipay/sofa-boot#35]
Spring Boot 2.0 is released, and SOFA boot should upgrade Spring Boot version to 2.0

**Comment by itsuifeng** [comment]
spring-boot-starter-actuator:2.0.0-RELEASE endpoint API has changed. 
healthcheck-sofa-boot-starter need to upgrade.

**Comment by icc99** [comment]
@guanchao-yang  怎么验证? 我看到现在的master分支, 用的还是sb 1.4.2.RELEASE

**Comment by guanchao-yang** [comment]
@icc99 
是的。目前还是 1.4.2.RELEASE。升级 2.X 后，保证 SOFABoot 所有测试用例都通过，如工程子模块的 HealthCheck ，然后我们再发版前也会推进所有 SOFABoot 管控的组件验证通过。

可以 PR ，保证我们的 SOFABoot 工程测试用例通过，然后再根据修改添加相应的一些测试用例哈。PR 时，我们已经默认集成了 [travis-ci](https://travis-ci.org/alipay/sofa-boot)

**Comment by xumengsi** [comment]
期待支持springboot2

**Comment by soulkingz** [comment]
1.4.2.RELEASE版本有点老了，针对1.5.X有做过测试吗？
另外非常期待支持2.X的版本能早日RELEASE
