### ISSUE TITLE
sofa-version-maven-plugin没有开源？

### ISSUE THREAD

**Issue by SoftwareKing** [alipay/sofa-boot#358]
访问https://github.com/ant-tech-alliance/sofa-version-maven-plugin出现404

**Comment by QilongZhang** [comment]
嗯，这还是内部一个工具包，还没有开源，现在你是有什么诉求？

**Comment by SoftwareKing** [comment]
@QilongZhang 好奇既然安装到中央仓库上，想看一下

**Comment by QilongZhang** [comment]
@SoftwareKing  👌，之前只上传了jar包到仓库，现在内部还在走开源流程，近期会开出来。
