### ISSUE TITLE
sofa-boot-sample demo parent改成sofaboot-dependencies2.6.1，服务起不来

### ISSUE THREAD

**Issue by itrickzhang** [alipay/sofa-boot#359]
![image](https://user-images.githubusercontent.com/23379828/53158840-86711000-35ff-11e9-9ce2-4f455f0c1621.png)

**Comment by QilongZhang** [comment]
看日志你应该是一个非web系统，没有非 daemon 线程启动又关闭了。

**Comment by itrickzhang** [comment]
![image](https://user-images.githubusercontent.com/23379828/53212718-04c1c680-3681-11e9-8518-9a44b479aa38.png)
这是我demo项目所有的依赖，当parent sofaboot-dependencies版本是3.1.0可以正常启动，版本为2.6.1，就用该问题

**Comment by QilongZhang** [comment]
@itrickzhang   麻烦将 demo 上传下，我看下问题？

**Comment by itrickzhang** [comment]
[sofaboot-sample.zip](https://github.com/alipay/sofa-boot/files/2891987/sofaboot-sample.zip)
已上传

**Comment by QilongZhang** [comment]
@itrickzhang  上传的文件似乎有问题，一直解压失败。

**Comment by itrickzhang** [comment]
https://github.com/itrickzhang/sofaboot-sample   
demo已上传到github

**Comment by 1990lsf** [comment]
@itrickzhang 
我clone了你的项目，使用2.6.1版本是可以启动的，
![image](https://user-images.githubusercontent.com/3351027/53236102-76743180-36ce-11e9-925c-1471867c2425.png)
这样看是并没有使用sofaboot,我在pom.xml中添加了
`<dependency>
			<groupId>com.alipay.sofa</groupId>
			<artifactId>isle-sofa-boot-starter</artifactId>
		</dependency>`
也是可以启动的启动。

**Comment by QilongZhang** [comment]
@itrickzhang  确实如 @1990lsf  所说，sample 在2.6.1 是可以正常启动的。 另外demo只是引入了 sofaboot-dependencies  头，并没有引入 SOFABoot 相关任何 starter.
