### ISSUE TITLE
English syntax is poor in the introduction

### ISSUE THREAD

**Issue by eadren** [alipay/sofa-boot#36]
SOFABoot is a framework that enhances Spring Boot and fully compatible with it, provide readiness check, class isolation, etc.

"compatible" is a adj not verb and "provide" should be "provides"

**Comment by khotyn** [comment]
@eadren Thank you for your advise, already change "provide" to "provides". I just check oxford dictionary, "is compatible with" is wildly used, so I think this is not a problem

<https://en.oxforddictionaries.com/definition/compatible>
