### ISSUE TITLE
typo in JvmBindingAdapter$JvmServiceInvoker

### ISSUE THREAD

**Issue by hqq2023623** [alipay/sofa-boot#360]
JvmBindingAdapter.java 
line 192 
``` java
cant not find the corresponding JVM service
```
change  "cant not " to "can not "

## Environment:
branch : master && 2.x
version : 3.1.2-SNAPSHOT && 2.6.0-SNAPSHOT

**Comment by QilongZhang** [comment]
感谢~ 3.1.2 已改，2.x 分支期待你 PR 改呢。

**Comment by hqq2023623** [comment]
I can get it fixed tonight
