### ISSUE TITLE
什么时候升级到springboot 2.1.1以后的版本

### ISSUE THREAD

**Issue by mail6562** [alipay/sofa-boot#367]
什么时候升级到springboot 2.1.1以后的版本，2.1.0之前的版本类加载器有bug。 eureka 启动有bug。
有做类似于dubbo admin 的后台管理系统吗，方便做服务上线下线。

**Comment by QilongZhang** [comment]
@mail6562  能说名下是哪个bug吗，官方对应的issue说是哪个，看了官方发布报告，没找到classloader相关的bugfix.

**Comment by QilongZhang** [comment]
这个 issue 我先关闭了，有问题可以重开回复。
