### ISSUE TITLE
jvm调用出现会丢掉方法入参的对象的改变值

### ISSUE THREAD

**Issue by grindwheel** [alipay/sofa-boot#374]
问题描述：
1、已知SOFA应用A,应用B，存在A.handleRequest(ReqContext)，由B应用实现handleRequest(ReqContext)并暴露服务了，但实现过程中，把处理的中间结果set到ReqContext中，结果A调用handleRequest(ReqContext)后，拿不到ReqContext的中间结果？
![image](https://user-images.githubusercontent.com/10232714/54127265-57063400-4444-11e9-9d29-6c2456d9afaa.png)

**Comment by QilongZhang** [comment]
合并部署之间的 JVM 服务调用默认是会走序列化，服务端回写参数对象的值，客户端是不能感知的，因为序列化的原因，已经是两个不同对象了。

可以尝试使用 v3.1.3 版本提供的跳过 jvm 序列化特性来避开这个问题。https://github.com/alipay/sofa-boot/issues/369

具体使用可以参考 [Demo](https://github.com/QilongZhang/test-jvm-invocation)，里面有 README 说明。
