### ISSUE TITLE
模块隔离后的数据库链接如何共享？

### ISSUE THREAD

**Issue by kazaff** [alipay/sofa-boot#375]
大家好，请问，在模块的容器隔离或底层类隔离后，像数据库连接池这样的资源（例如整合Mybatis），如何跨模块或组件包共享呢？

**Comment by QilongZhang** [comment]
可以将数据库下沉为插件，在宿主应用中初始化数据源，并发布成 JVM 服务，其他应用引用该服务。

可以先参考这个 [Demo](https://github.com/QilongZhang/test-jvm-invocation)，它介绍的是如何直接使用其他应用（模块）定义的定时任务  Quartz Job.  专门针对数据连接池共享的 Demo 准备中。

**Comment by kazaff** [comment]
@QilongZhang 感激不尽

**Comment by kazaff** [comment]
@QilongZhang 

希望专门针对数据库连接池共享的demo中，能涉及到mybatis整合的内容，尤其是共享数据连接池后，多个模块间协作时的事务问题。谢谢~
