### ISSUE TITLE
请教关于模块隔离中的模块和类隔离中的插件的区分？

### ISSUE THREAD

**Issue by kazaff** [alipay/sofa-boot#376]
在看SOFABoot文档的时候，一直高不太清楚两个概念：
1. 模块隔离中的模块
2. 类隔离中提到的biz plugin or ark plugin

首先，模块的隔离方式是spring context，而plugin是classloader。
但从设计层面上如何区分模块和插件（biz）呢？例如哪些层适合以哪种方式组织呢？

另外，在模块隔离文档中，提到:

> 不建议也不支持在 SOFABoot 模块中定义 Controller 组件，Controller 组件相关定义请直接放在 Root Application Context。

而在ark plugin的[发展路线](https://www.sofastack.tech/sofa-boot/docs/sofa-ark-roadmap)提到会支持多个biz各自包含web层。

这是否可以理解为：

**每个biz plugin包含部分业务，多种业务组合成一个module？**

**Comment by kazaff** [comment]
另外，没有看到“模块打包”的文档，好像模块是不需要单独打包的吧~这样的话似乎有点明白了~

**Comment by QilongZhang** [comment]
***首先需要明确一点的是：模块和Ark是两个完全不相关的概念***

SOFA模块属于应用的的一部分，SOFABoot 定义的一种 Java 模块形式，可以[参考文档](https://www.sofastack.tech/sofa-boot/docs/SOFABoot-Module)，特的特殊之处在于，应用启动期间，每个 SOFA模块是单独的应用上下文，但是是同一个 ClassLoader 加载，它解决的问题或者说优势可以[参考文章](https://www.sofastack.tech/posts/2018-07-25-01)。简单来说，SOFA 模块是 SOFABoot 提供的一种模块化开发方案。

biz，plugin 是 SOFAArk 包含的概念，SOFAArk 提供了类隔离以及应用合并部署的能力，每个 Biz 是一个应用，他可以是 Spring Boot 也可以是 SOFABoot ，甚至是普通的 Java 应用。运行时每个 Biz 都是由单独的 ClassLoader 加载；

最后，SOFA模块和 SOFAArk 中的 Biz 是两个不同维度的模型关系。可能只有一点是相似的，他们都是通过同一个的编程界面(@SofaService/@SofaReference) 进行交互。

**Comment by kazaff** [comment]
@QilongZhang 谢谢解答

**Comment by wangmin-xidian** [comment]
@QilongZhang 
那是否可以理解为：
- 模块化开发类似于是不同功能的多个project，并行开发。开发和编译期是模块隔离的，最后部署运行时，是同一个ClassLoader加载运行的。
 - SOFAArk针对同一个project中，使用到了同一个jar的不同版本带来的冲突，将一个version的jar build成plugin，新的ClassLoader会加载使用。同样的原理，Biz是更高层级的应用程式，不同的ClassLoader加载不同的Biz。

**Comment by QilongZhang** [comment]
@wangmin-xidian  
> 开发和编译期是模块隔离的
不一定是这样，SOFABoot 中的模块是应用启动后，Spring 上下文隔离，模块有特定的格式，上面回答中贴出的文章链接看下。

同理理解 SOFAArk 的原理和解决的问题，上面你列出的场景只是他们解决的一部分问题，站在底层原理实现上理解更好。

**Comment by wangmin-xidian** [comment]
@QilongZhang  Thanks.
才开始了解SOFA开源组件，只是站在需求方面去理解这个问题。还需多多研究和实践吧，感谢。
