### ISSUE TITLE
关于sofaboot框架代码的一些疑问

### ISSUE THREAD

**Issue by githubyangxd** [alipay/sofa-boot#389]
针对框架的整体以及各个模块主要功能，模块间关系的介绍，目前没看到，“开源社区”快速开发模块介绍的太简略啦。

**Comment by QilongZhang** [comment]
@githubyangxd  https://www.sofastack.tech/sofa-boot/docs/Home 官方文档主要按 SOFABoot 框架的功能描述，而不是按照具体的 Starter 划分。SOFABoot 主要包含的 Starter 及对应的功能

+ healthcheck-sofa-boot-starter 
> 提供健康检查

+ infra-sofa-boot-starter
> 版本查看等基础能力

+ runtime-sofa-boot-starter
> JVM 服务发布引用、扩展点、Bean 异步初始化等能力

+ isle-sofa-boot-starter
> 模块上下文隔离能力

+ test-sofa-boot-starter
> 测试功能模块

模块的快速开发 Demo 是： https://github.com/alipay/sofa-boot/tree/master/sofaboot-samples/sofaboot-sample-with-isle
