### ISSUE TITLE
关于demo中sofa-boot-sample模块启动问题

### ISSUE THREAD

**Issue by githubyangxd** [alipay/sofa-boot#390]
下载sofa-boot-master工程到本地，启动 sofa-boot-sample模块启动类后无法访问http://localhost:8080/actuator/readiness查看“状态”，需要在当前模块的pom文件中添加 如下两个依赖：
<dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-config</artifactId>
        </dependency>
是我理解的不对还是demo中本就应该添加进来？
 按照社区文档中的“快速开始”模块中一段话：“附此示例工程的源代码地址。”(链接为：https://github.com/alipay/sofa-boot/tree/master/sofaboot-samples/sofaboot-sample)引导进入的就是  sofa-boot/sofaboot-samples/sofaboot-sample/，
由此存在问题有3（有可能是我理解不对）：
1.demo中是否应该完善添加上那两个依赖（针对spring boot用的不6的选手）？
2.或者在“快速开始” 文档中是否应该说明需要添加这两个依赖？
3.如果这是个问题的话，在demo中是否还存在别的类似的问题，如果存在，是否会在第一时间更新，以及通告一下。
（PS:社区文档能在描述的详细点么，初级选手读起来有点费劲，且是否考虑按照一定的逻辑进行文档的编写）
感谢您阅读这么啰嗦的￥%……&*，耽误您宝贵的时间请谅解，我也是希望社区能更大众化一点，容易让更多的人用起来！

**Comment by QilongZhang** [comment]
非常感谢，反馈的示例中需要添加 web 依赖，不过 spring-cloud-starter-config 依赖不需要添加，示例和 Spring Cloud  无关。

[快速开始](https://www.sofastack.tech/sofa-boot/docs/QuickStart) 其实是已经说明了需要添加 web 依赖以及健康检查依赖的，可以再仔细阅读下文档。

解释下 web 依赖缺失的原因，在早期版本 healthcheck-sofa-boot-starter 是会默认引入 web 依赖的，所以当时并没有加上，感谢反馈。

关于文档的逻辑，期待在[文档工程](https://github.com/alipay/sofastack-doc/pulls) 以 PR 的形式给我们提供下建议哈。
