### ISSUE TITLE
SOFABoot的模块和SOFAArk的Ark包之间有什么关系?

### ISSUE THREAD

**Issue by TomorJM** [alipay/sofa-boot#391]
看了文档感觉有点蒙~

**Comment by QilongZhang** [comment]
参考下 https://github.com/alipay/sofa-boot/issues/376

**Comment by QilongZhang** [comment]
梳理部分文档描述，该问题可以参考 FAQ https://www.sofastack.tech/sofa-boot/docs/FAQ
