### ISSUE TITLE
模块隔离和类隔离能一起共用吗？

### ISSUE THREAD

**Issue by myprogo** [alipay/sofa-boot#396]
模块隔离和类隔离能一起共用吗？

**Comment by QilongZhang** [comment]
嗯，可以共用。 模块隔离是应用内部的概念，是由同一个ClassLoader 加载。 类隔离是中定义的 Biz 模型是应用级别，应用内部是否使用模块隔离不做限制。可以参考 FAQ https://www.sofastack.tech/sofa-boot/docs/FAQ
