### ISSUE TITLE
官方isle demo中的provider和consumer中添加同名component, 运行run提示bean冲突

### ISSUE THREAD

**Issue by TomorJM** [alipay/sofa-boot#397]
![image](https://user-images.githubusercontent.com/11410549/56705876-5cde7d00-6745-11e9-873b-1df5866832a0.png)

**Comment by TomorJM** [comment]
![image](https://user-images.githubusercontent.com/11410549/56705830-3587b000-6745-11e9-98b9-d299ebd39b4d.png)

**Comment by QilongZhang** [comment]
你添加的 DemoManager 都在包名 `com.alipay.sofa.isle.sample`，猜测你都是使用注解的形式将 DemoManager 发布 Bean 的。而启动类为  `com.alipay.sofa.isle.sample.ApplicationRun`， 会默认扫描 `com.alipay.sofa.isle.sample` 包下的所有组件，导致你添加的两个 DemoManager 实际都在 Root Context 中了。

**Comment by TomorJM** [comment]
这里有个问题:
1: 我将@Component注解声明bean的方式改为在xml中加载
![image](https://user-images.githubusercontent.com/11410549/56706612-3cfc8880-6748-11e9-85ff-e37cb420b61b.png)
![image](https://user-images.githubusercontent.com/11410549/56706641-51408580-6748-11e9-9ae5-b6f59f1abbfa.png)
启动后就不存在冲突问题, 按照您上述说法, 那是否可以这样理解:
这时候DemoManager都各自存在于各自的模块中, 而不是Root Context
2: 为什么两种生命注解的方式会有这样的差别

**Comment by QilongZhang** [comment]
应用的启动入口是  com.alipay.sofa.isle.sample.ApplicationRun， Spring  Boot 官方逻辑就是会扫描入口类所在的包 `com.alipay.sofa.isle.sample.` 中所有的 Component，所以你定义的 DemoManager 都会被扫进 Root Context，xml 的解析则是 SOFABoot 自己扫描的。

**Comment by TomorJM** [comment]
> 应用的启动入口是 com.alipay.sofa.isle.sample.ApplicationRun， Spring Boot 官方逻辑就是会扫描入口类所在的包 `com.alipay.sofa.isle.sample.` 中所有的 Component，所以你定义的 DemoManager 都会被扫进 Root Context，xml 的解析则是 SOFABoot 自己扫描的。

恩恩,这个了解了,麻烦看下问题3~

**Comment by QilongZhang** [comment]
@TomorJM   目前无法做到自动甄别，主要还是没有一个很完美的方案，欢迎贡献思路~
