### ISSUE TITLE
sofaboot-sample-with-isle并没有spring上下文隔离

### ISSUE THREAD

**Issue by bongQ417** [alipay/sofa-boot#399]
sofaboot-sample-with-isle并没有spring上下文隔离，
我再不同的bundle上使用@Service和@Autowired，都可以取到对象，并且bundle的Require-Module配置已经删除了

**Comment by QilongZhang** [comment]
听描述似乎是改了代码，你可以上传下你的 demo.

**Comment by bongQ417** [comment]
> 听描述似乎是改了代码，你可以上传下你的 demo.

https://github.com/bongQ417/sofa-demo
看提交记录即可，谢谢

**Comment by bongQ417** [comment]
@QilongZhang

**Comment by QilongZhang** [comment]
https://github.com/alipay/sofa-boot/issues/397  和这个问题是类似的，都被扫描进 Root Context 了
