### ISSUE TITLE
将SOFABoot模块打包成一个jar包, 在宿主应用上应该如何以正确的方式引用该Jar包?

### ISSUE THREAD

**Issue by TomorJM** [alipay/sofa-boot#400]
在pom文件中引入该jar包, 使用JVM服务一直报错找不到。正确方式是什么?

**Comment by TomorJM** [comment]
真的无语了,搞了一晚上

**Comment by QilongZhang** [comment]
麻烦提供下问题 demo

**Comment by TomorJM** [comment]
[demo](https://github.com/TomorJM/SOFABootDemo)

**Comment by TomorJM** [comment]
@QilongZhang 
Demo中有四个模块
facade、contract、info需要执行下mvn install发布到本地
supplier作为宿主web应用启动后调用localhost:8080/test报错
![image](https://user-images.githubusercontent.com/11410549/56863223-620e2700-69e6-11e9-9c35-d35d96258160.png)

**Comment by TomorJM** [comment]
@QilongZhang 在看了吗, 急~

**Comment by QilongZhang** [comment]
参考文档： https://www.sofastack.tech/sofa-boot/docs/SOFABoot-Module

你的 xml 文件放错了目录了(resource/spring/*)，应该放在(resource/META-INF/spring/*)
