### ISSUE TITLE
关于模块间事务的一些疑惑

### ISSUE THREAD

**Issue by TomorJM** [alipay/sofa-boot#401]
1.模块间JVM服务调用
app中有两个模块A和B, A调用B提供的JVMService。
- 如果A和B模块都有自己的数据源, 那么这时能否保证事务性(能否提供下姿势)。或者有没有好的解决方案?
- 如果数据源下沉到app测做, 那么A和B的数据源统一由APP管理, 那么会加大模块迁移的复杂度, 这时蚂蚁内部有没有好的姿势可以借鉴

2.模块间RPC调用
app1:模块A, app2:模块B ,A调用B的RPCService
这时事务是采用DTX方式解决的嘛?

**Comment by zhangthen** [comment]
你这是跨服务、跨数据事务问题，可看下蚂蚁金服另一个开源项目：https://github.com/seata/seata ，
Seata 是分布式事务开源产品，用于解决跨数据库跨服务事务问题。

**Comment by TomorJM** [comment]
> 你这是跨服务、跨数据事务问题，可看下蚂蚁金服另一个开源项目：https://github.com/seata/seata ，
> Seata 是分布式事务开源产品，用于解决跨数据库跨服务事务问题。

那问题1中的不同模块间的跨数据源, SOFABoot本身是无法解决的对吗~
那模块共享一个数据源, 模块间JVM服务调用是可以保证事务的嘛~

**Comment by QilongZhang** [comment]
@TomorJM  你说的保证事务指哪方面？ JVM 服务调用和能不能保证事务没有必然关系，JVM 服务调用只是在普通 Bean 之上包装了一层代理，本质上就是jvm内部的的一个普通类方法调用。

**Comment by zhangthen** [comment]
> > 你这是跨服务、跨数据事务问题，可看下蚂蚁金服另一个开源项目：https://github.com/seata/seata ，
> > Seata 是分布式事务开源产品，用于解决跨数据库跨服务事务问题。
> 
> 那问题1中的不同模块间的跨数据源, SOFABoot本身是无法解决的对吗~
> 那模块共享一个数据源, 模块间JVM服务调用是可以保证事务的嘛~

SOFABoot 要集成 分布式事务产品才能具备 跨数据源事务能力；
“那模块共享一个数据源, 模块间JVM服务调用是可以保证事务的嘛~”  跨模块如果没跨 线程的话，你可以用普通的数据库事务来保证事务，如果跨了线程就只能接入 分布式事务产品了

**Comment by TomorJM** [comment]
> > > 你这是跨服务、跨数据事务问题，可看下蚂蚁金服另一个开源项目：https://github.com/seata/seata ，
> > > Seata 是分布式事务开源产品，用于解决跨数据库跨服务事务问题。
> > 
> > 
> > 那问题1中的不同模块间的跨数据源, SOFABoot本身是无法解决的对吗~
> > 那模块共享一个数据源, 模块间JVM服务调用是可以保证事务的嘛~
> 
> SOFABoot 要集成 分布式事务产品才能具备 跨数据源事务能力；
> “那模块共享一个数据源, 模块间JVM服务调用是可以保证事务的嘛~” 跨模块如果没跨 线程的话，你可以用普通的数据库事务来保证事务，如果跨了线程就只能接入 分布式事务产品了

了解了~
分布式事务框架内部实践是用的[DTX](https://tech.antfin.com/products/DTX)还是Seata? SOFABoot对两者都可兼容使用

**Comment by zhangthen** [comment]
> 分布式事务框架内部实践是用的[DTX](https://tech.antfin.com/products/DTX)还是Seata? SOFABoot对两者都可兼容使用

DTX 是我们的商业版，要花钱买的;Seata 是我们的开源版，可以免费体验；
