### ISSUE TITLE
 Failed to retrieve 'health' endpoint data

### ISSUE THREAD

**Issue by myprogo** [alipay/sofa-boot#402]
使用了模块隔离和类隔离，加载健康检查时提示这个：
` Failed to retrieve 'health' endpoint data`

**Comment by QilongZhang** [comment]
麻烦提供下 demo

**Comment by myprogo** [comment]
[demo.zip](https://github.com/alipay/sofa-boot/files/3145099/demo.zip)

**Comment by QilongZhang** [comment]
你在代码中使用了 SOFAArk 启动方式，runtime-sofa-boot-starter 应该替换采用引入 ark plugin 的方式，引入如下依赖：
```xml
        <dependency>
            <groupId>com.alipay.sofa</groupId>
            <artifactId>runtime-sofa-boot-plugin</artifactId>
        </dependency>
```
