### ISSUE TITLE
启动提示Sofa-Middleware-Log:WARN No log util is usable, Default app logger will be used.

### ISSUE THREAD

**Issue by myprogo** [alipay/sofa-boot#403]
启动提示：
`SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Sofa-Middleware-Log:WARN No log util is usable, Default app logger will be used.`

这个Sofa-Middleware-Log怎么管理？

**Comment by QilongZhang** [comment]
报错应该是因为你在工程中没有引入具体的日志实现，比如log4j2, logback.
