### ISSUE TITLE
模块化后每个模块的配置文件的问题

### ISSUE THREAD

**Issue by myprogo** [alipay/sofa-boot#405]
比如有以下模块：common、core、module-pa、module-oa、module-hr、plugin-district和bootstrap等等，将模块和插件类的全部分开。现在模块化后每个模块的配置文件，是在自己模块目录下的resources文件夹里建application.yml，还是将所有的配置文件都放在bootstrap下的application.yml里？

**Comment by QilongZhang** [comment]
嗯，配置文件都是共用的。

**Comment by TomorJM** [comment]
我觉得可以尝试配置文件设计成"模块自包含"
ROOT -> resource
Module A -> resourceA
Module B -> resourceB

A和B可以共享SystemProperties, 但是各自又有独立且在配置在自己模块包内的自定义配置文件
尤其是使用类似于 **@Value("${test}")** 注解的场景下, 独立且自包含的配置不管在模块设计上还是对模块化的理解更加有利

**Comment by QilongZhang** [comment]
> 我觉得可以尝试配置文件设计成"模块自包含"
> ROOT -> resource
> Module A -> resourceA
> Module B -> resourceB
> 
> A和B可以共享SystemProperties, 但是各自又有独立且在配置在自己模块包内的自定义配置文件
> 尤其是使用类似于 **@value("${test}")** 注解的场景下, 独立且自包含的配置不管在模块设计上还是对模块化的理解更加有利

模块是应用下的维度，模块的划分更多是业务逻辑模块的划分，整体构建成完整的应用。作为配置文件，应该是和应用同纬度的，因此在设计上并没有给模块单独配置，结合蚂蚁内部实际，也似乎并未受到类似的需求。

**Comment by TomorJM** [comment]
个人认为模块也是需要高内聚的, 不管是从业务角度, 模块设计亦或是部署态都是如此, 因为模块是有可能从一个应用迁移到另一个应用上面去的, 且迁移过程最好不需要改动任何配置(仅仅需要改动Sofa上的模块依赖配置和pom即可)
