### ISSUE TITLE
sofaboot-sample-standard里面为何没有核心领域层，core层？

### ISSUE THREAD

**Issue by JinAirsOs** [alipay/sofa-boot#407]
感觉core层还是很重要的，发布一个rpc service的facade的时候经常需要使用common-dal里的model，但是却没办法，只能重复定义同一个差不多功能的model甚至DO，感觉还是有core层直接继承了common-dal里的model然后再在core-service里面定义facade要更合适，为什么删掉了这么重要的一层？后续有选择加进来么？

**Comment by QilongZhang** [comment]
demo 比较简单，没有考虑你说的这些业务分层。Demo 重点是为了演示在 SOFA 多模块下面如何使用数据源，提供简单的增删改查功能。
