### ISSUE TITLE
Make infra's dependency on spring-boot-starter-actuator optional 

### ISSUE THREAD

**Issue by caojie09** [alipay/sofa-boot#64]
Make infra's dependency on spring-boot-starter-actuator optional

**Comment by QilongZhang** [comment]
Could you describe what's the reason?

**Comment by QilongZhang** [comment]
If make infra's dependency on `spring-boot-starter-actuator` optional, it seems to lead endpoint unusable, unless project add `spring-boot-starter-actuator` dependency in its pom file. @caojie09

**Comment by QilongZhang** [comment]
also  `spring-boot-starter-web` should be set optional
