### ISSUE TITLE
SOFABoot 代码阅读发现的一些问题

### ISSUE THREAD

**Issue by QilongZhang** [alipay/sofa-boot#66]
+ SofaBootLogSpaceIsolationInit 原打算应该是做初始化日志的公用类，但是现在runtime、infra、healthcheck都是各自初始化，一些代码也是重复执行
+ 注释有些地方是直接copy的，和代码不契合，如 InfraHealthCheckLoggerFactory类第48行注释。 另外 Javadoc 标签有些地方没用好
+ SofaBootVersionEndpoint 普通的 endpoint 和 mvcendpoint 共存，在设置disable/enable时会存在bug, 需要使用 `@ConfigurationProperties` 配置相同的 prefix
+ 建议所有的版本信息都继承 AbstractSofaBootMiddlewareVersionFacade 接口，而不需要分成两种不同的形式处理，另外该 RuntimeInfo 方法返回空map，不要返回null。
+ HealthCheckConfigurationConstants 中删除不用的变量，有些变量其他地方有定义。另外这类一部分功能用于获取环境变量，不够 SpringBoot 风格，可以尝试换成 `@ConfigurationProperties` 注解
+ SofaBootReadinessCheckEndpoint 同样有 SofaBootVersionEndpoint 一样的问题
+ DefaultHealthChecker 是一个抽象类，按照其作用，命名 AbstractHealthCheckerAdapater 可能更好，或者不要定义成抽象类
+ 代码很多无端的空行分隔，比如 com.alipay.sofa.healthcheck.startup.ReadinessCheckProcessor#startHealthCheckProcess
+ com.alipay.sofa.healthcheck.core.ComponentCheckProcessor#httpCheckComponent 日志打印错误，另外建议名字改成liveness check
+ HealthCheckManager 有不少从 ApplicationContext 拿特定类型的类，可以封装一下成`getBeansOfType(Class, Filter)`
+ 有 SofaBootBeforeReadinessCheckEvent ，但是没有对应的 After 事件，而是换成了 Callback 接口，这一块能不能同意下？
+ Component 类 85 行注释错误
+ referenceImpl 和 serviceImpl 改下 toString 需要改下，需要拼装上 uniqid

**Comment by straybirdzls** [comment]
点个赞～ 另外应该可以根据之前总结的那些经验整体检查一遍😄

**Comment by straybirdzls** [comment]
点个赞～ 另外应该可以根据之前总结的那些经验整体检查一遍😄

**Comment by QilongZhang** [comment]
@straybirdzls 好的

**Comment by QilongZhang** [comment]
SofaBootVersionEndpoint/SofaBootReadinessCheckEndpoint 提供了enable/disable开关控制：
+ `com.alipay.sofa.versions.enabled` 控制 `sofaboot/versions` 的访问，默认开启
+ `com.alipay.sofa.healthcheck.readiness` 控制 `health/readiness` 的访问，默认开启

**Comment by guanchao-yang** [comment]
> com.alipay.sofa.healthcheck.readiness 控制 health/readiness 的访问，默认开启

@QilongZhang 这里应该有个 enable 的标识吧？

**Comment by khotyn** [comment]
@QilongZhang Can you assign this issue to a specific milestone or project, so we can figure out which version solve this problem more quickly later.
