### ISSUE TITLE
替换rest序列化包

### ISSUE THREAD

**Issue by qinliang373** [alipay/sofa-boot#70]
最近在使用rest协议时，返回实体属性默认使用了codehaus这个序列化包（在返回实体属性上加上codehaus的注解有效，使用其他的(fastxml,fastjson,sofarpc的都无效），如何才能改变返回序列包？请大神赐教

**Comment by khotyn** [comment]
可以再详细点描述下你的问题吗？如果可以的话，附上一些示例的代码以说明问题。

**Comment by qinliang373** [comment]
写了一个pageRequest接收分页参数实体类，机构类继承pageRequest类
public class PageRequest {
	
	public static final Integer PAGE_SIZE = 15;
	public static final Integer PAGE_NUM = 1;
	private Integer pageNum;
	private Integer pageSize;
	public Integer getPageNum() {
		return pageNum;
	}
	public void setPageNum(Integer pageNum) {
		this.pageNum = pageNum;
	}
	public Integer getPageSize() {
		return pageSize;
	}
	public void setPageSize(Integer pageSize) {
		this.pageSize = pageSize;
	}
	
	public Page startPage() {
		if(pageNum == null) {
			pageNum = PAGE_NUM;
		}
		if(pageSize == null) {
			pageSize = PAGE_SIZE;
		}
		return PageHelper.startPage(pageNum,pageSize);
	}
}
进行查询组织
//此处为接口
@POST
@Path("/pageList")
Result<PageInfo<Organization>> findOrganizationsByPage(Organization organization);
方法入参：
{
	"pageNum":1,"pageSize":1
}
输出结果部分数据（分页部分省略了）：
{
    "code": "200",
    "success": true,
    "model": {
        "total": 2,
        "list": [
            {
                "pageNum": null,
                "pageSize": null,
                "id": 1,
                "orgType": "HEAD_OFFICE",
                "parentId": 0,
                "parentIds": "0/",
                "icon": "",
                "deleted": 0
            }
        ]
    "message": "查询成功"
}
在输出中不需要序列化属性pageNum和pageSize，在 pageNum和pageSize上加       @org.codehaus.jackson.annotate.JsonIgnore注解会造成{"pageNum":1,"pageSize":1}入参也不成功，但codehaus.jackson版本没找到忽略空性的注解，有什么方法解决？或有什么方法序列性json采用 fastjson或fastxml的版本？

**Comment by qinliang373** [comment]
是的，通过SOFARPC来发布restful服务，传参和返回都是以json格式。

**Comment by ScienJus** [comment]
@qinliang373  旧版本的 jackson 应该是可以配置只使用 setter 不使用 getter 的，但是因为它的实现，你必须在 getter 中添加 `@JsonIgnore` 的同时，在 setter 中添加 `@JsonProperty`，应该就可以了。

这是相关文档：

> In addition, starting with Jackson 1.9, if this is the only annotation associated with a property, it will also cause cause the whole property to be ignored: that is, if setter has this annotation and getter has no annotations, getter is also effectively ignored. It is still possible for different accessors to use different annotations; so if only "getter" is to be ignored, other accessors (setter or field) would need explicit annotation to prevent ignoral (usually JsonProperty).
> 
> For example, a "getter" method that would otherwise denote a property (like, say, "getValue" to suggest property "value") to serialize, would be ignored and no such property would be output unless another annotation defines alternative method to use.

这是一个 demo：

```
public static class Page {

    private int page;

    private int count;

    @JsonIgnore
    public int getPage() {
        return page;
    }

    @JsonProperty
    public void setPage(int page) {
        this.page = page;
    }

    @JsonIgnore
    public int getCount() {
        return count;
    }

    @JsonProperty
    public void setCount(int count) {
        this.count = count;
    }

    public String getInfo() {
        return "page: " + page + ", count: " + count;
    }
}

public static void main(String[] args) throws IOException {
    ObjectMapper objectMapper = new ObjectMapper();
    Page page = objectMapper.readValue("{\"page\":1,\"count\":15}", Page.class);
    System.out.println(objectMapper.writeValueAsString(page));
}
```

**Comment by khotyn** [comment]
@qinliang373 可以尝试用 @ScienJus 的方式解决一下。我在我的机子上试了一下，使用的 jackson 的版本是 1.9.12，用 `JsonIgnore` 注解就可以了。

![image](https://user-images.githubusercontent.com/584455/40586679-1d49ee2a-61f8-11e8-8fd9-b4e8445d50b3.png)

**Comment by qinliang373** [comment]
感谢大神细心、专业的指导，采用@JsonIgnore与 @JsonProperty注解可以解决我的问题，弱弱的问下 @ScienJus 的方式指的是哪种方式，可以给个链接或代码示例吗（目前我的jackson版本是一样的）？

**Comment by khotyn** [comment]
@qinliang373 就是他在这个 ISSUE 中回复的方式，可以稍微往上翻一下。

![image](https://user-images.githubusercontent.com/584455/40596725-58d0639e-626f-11e8-92a6-a2ff908eb901.png)

**Comment by qinliang373** [comment]
好的，感谢大神热心专业的解答

**Comment by khotyn** [comment]
这个问题我先关掉了，有问题的话，请再打开。 @qinliang373

**Comment by qinliang373** [comment]
好的
