### ISSUE TITLE
Provide a SOFABoot banner

### ISSUE THREAD

**Issue by leizhiyuan** [alipay/sofa-boot#72]
maybe we need to provide a banner to increase brand identity

```
${AnsiColor.BRIGHT_GREEN}
 ,---.    ,-----.  ,------.   ,---.     ,-----.                     ,--.
'   .-'  '  .-.  ' |  .---'  /  O  \    |  |) /_   ,---.   ,---.  ,-'  '-.
`.  `-.  |  | |  | |  `--,  |  .-.  |   |  .-.  \ | .-. | | .-. | '-.  .-'
.-'    | '  '-'  ' |  |`    |  | |  |   |  '--' / ' '-' ' ' '-' '   |  |
`-----'   `-----'  `--'     `--' `--'   `------'   `---'   `---'    `--'

Ant Financial Services Group
${AnsiColor.BRIGHT_RED}
Spring Boot Version: ${spring-boot.version}${spring-boot.formatted-version}
```

this wil show a banner like 

![image](https://user-images.githubusercontent.com/2684384/40586176-d2598062-61f0-11e8-9f78-6e481e3a28d0.png)

**Comment by QilongZhang** [comment]
@leizhiyuan  I plan to add sofaboot/spring boot version info in banner.txt. like this:
![image](https://user-images.githubusercontent.com/8833026/42798232-62f06a04-89c5-11e8-96b9-a3aa78556177.png)
