### ISSUE TITLE
sofarpc restful增加项目前缀的问题

### ISSUE THREAD

**Issue by qinliang373** [alipay/sofa-boot#77]
使用rest风格开发项目默认前缀是“/”，修改context-path只对springboot有效，查了些资料使用applicationPath注解或使用resteasy.servlet.mapping.prefix（在本机试了没生效），怎样在sofaboot的rest风格路径中加前缀？

**Comment by khotyn** [comment]
![image](https://user-images.githubusercontent.com/584455/40655931-5be5dc74-6375-11e8-9832-c4fae5bdcfd7.png)

直接在类上加上 `@Path` 注解即可。

**Comment by qinliang373** [comment]
就是说用一个全局常量来定义前缀吗？比如像这样@path(A.MFDATA+"/webapi")，有没有在配置文件中配置一个统一的前缀，就像springboot的server.context-path风格一样？

**Comment by qinliang373** [comment]
在每个路径上面手工引入统一的项目前缀有些太繁琐，希望能有像springboot的server.context-path风格配置

**Comment by ujjboy** [comment]
@qinliang373  嗯，需求了解了，需要将配置项读取出来，设置到`ServerConfig.setContextPath`下。

这个改造应该不难，你方便参与吗？

需要sofa-rpc-boot-projects工程下也做点改造。

**Comment by ujjboy** [comment]
@qinliang373  改造点请移步 https://github.com/alipay/sofa-rpc-boot-projects/issues/49 这个 Issue。 欢迎参与。

**Comment by khotyn** [comment]
@qinliang373 关于这个问题的进一步的讨论可以在 alipay/sofa-rpc-boot-projects#49 讨论，这里我先关闭掉了。

@ujjboy 已经在那个 issue 中写了大概涉及到的类以及思路， @qinliang373 你可以看下帮忙改下？

**Comment by qinliang373** [comment]
好的，感谢
