### ISSUE TITLE
导入sofa-rpc-boot-projects项目源码到sts出错

### ISSUE THREAD

**Issue by qinliang373** [alipay/sofa-boot#80]
本机安装jdk1.8，开发工具sts，将sofa-rpc-boot-projects导入sts出错，部分jar包找不到，
出错原因
Description	Resource	Path	Location	Type
Missing artifact com.alipay.sofa:healthcheck-sofa-boot-starter:jar:2.4.0	pom.xml	/sofa-boot-samples	line 31	Maven Dependency Problem
Missing artifact com.alipay.sofa:rpc-sofa-boot-starter:jar:5.4.0	pom.xml	/sofa-boot-samples	line 21	Maven Dependency Problem
Missing artifact com.alipay.sofa:test-sofa-boot-starter:jar:2.4.0	pom.xml	/sofa-boot-samples	line 26	Maven Dependency Problem
Plugin execution not covered by lifecycle configuration: com.googlecode.maven-java-formatter-plugin:maven-java-formatter-plugin:0.4:format (execution: default, phase: process-sources)	pom.xml	/sofa-boot-samples	line 7	Maven Project Build Lifecycle Mapping Problem
Plugin execution not covered by lifecycle configuration: org.jacoco:jacoco-maven-plugin:0.7.4.201502262128:prepare-agent (execution: pre-test, phase: process-classes)	pom.xml	/sse-boot-web-endpoint	line 5	Maven Project Build Lifecycle Mapping Problem
Plugin execution not covered by lifecycle configuration: org.jacoco:jacoco-maven-plugin:0.7.4.201502262128:prepare-agent (execution: pre-test, phase: process-classes)	pom.xml	/sse-boot-web-web	line 6	Maven Project Build Lifecycle Mapping Problem
Project build error: Non-resolvable parent POM for com.alipay.sofa:rpc-sofa-boot-starter:5.4.0: Failure to find com.alipay.sofa:sofaboot-dependencies:pom:2.4.0 in http://mvn.cloud.alipay.com/nexus/content/groups/public was cached in the local repository, resolution will not be reattempted until the update interval of mirror-all has elapsed or updates are forced and 'parent.relativePath' points at wrong local POM	pom.xml	/sofa-boot-starter	line 5	Maven pom Loading Problem
The container 'Maven Dependencies' references non existing library 'D:\javax\repo\com\alipay\sofa\rpc-sofa-boot-starter\5.4.0\rpc-sofa-boot-starter-5.4.0.jar'	sofa-boot-samples		Build path	Build Path Problem
The project cannot be built until build path errors are resolved	sofa-boot-samples		Unknown	Java Problem

**Comment by leizhiyuan** [comment]
你本地是不是配置了 alipay cloud的 mvn 库?
这个还没正式 release. 稍等下,今天会 release.

**Comment by qinliang373** [comment]
本地已经配置了alipay cloud的mvn库

**Comment by ujjboy** [comment]
@qinliang373  不会上传到 mvn.cloud.alipay.com 库  只会上传到Maven中央仓库。

**Comment by khotyn** [comment]
@qinliang373 开源的版本都是到 Maven 的中央仓库上的，不需要单独配置 alipay cloud 的 mvn 库的。

**Comment by Jiiiiiin** [comment]
也遇到同样的问题，本地可以，但是在进行ci的时候使用自建的nexus作为源就出现了：

```bash
$ mvn clean $MAVEN_CLI_OPTS $MAVEN_OPTS compile
[INFO] Scanning for projects...
[INFO] Downloading from maven-public: http://nexus.example.com:8081/repository/maven-public/com/alipay/sofa/sofaboot-dependencies/3.10.0/sofaboot-dependencies-3.10.0.pom
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for com.ynrcc.ebank:EBankCommLib:1.0.0: Could not transfer artifact com.alipay.sofa:sofaboot-dependencies:pom:3.10.0 from/to maven-public (http://nexus.example.com:8081/repository/maven-public/): transfer failed for http://nexus.example.com:8081/repository/maven-public/com/alipay/sofa/sofaboot-dependencies/3.10.0/sofaboot-dependencies-3.10.0.pom and 'parent.relativePath' points at no local POM @ line 8, column 11
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project com.ynrcc.ebank:EBankCommLib:1.0.0 (/builds/ebank/EBankCommLib/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for com.ynrcc.ebank:EBankCommLib:1.0.0: Could not transfer artifact com.alipay.sofa:sofaboot-dependencies:pom:3.10.0 from/to maven-public (http://nexus.example.com:8081/repository/maven-public/): transfer failed for http://nexus.example.com:8081/repository/maven-public/com/alipay/sofa/sofaboot-dependencies/3.10.0/sofaboot-dependencies-3.10.0.pom and 'parent.relativePath' points at no local POM @ line 8, column 11: Unknown host nexus.example.com: Name or service not known -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException
```
