### ISSUE TITLE
似乎 SofaRuntimeProperties 中的配置无法生效

### ISSUE THREAD

**Issue by ScienJus** [alipay/sofa-boot#87]
在我的项目中，通过 `application.yml` 设置 SofaRuntimeProperties 的配置无法生效，例如：

```
com.alipay.sofa.boot.disableJvmFirst=true
```

看了一下实现，这个配置最早会被 `ServiceAnnotationBeanPostProcessor` 作为其依赖进行加载，而 `@ConfigurationProperties` 是通过 `ConfigurationPropertiesBindingPostProcessor` 进行注入配置的。

在 Spring 上下文中所有 BeanPostProcessor 会在最开始进行加载，并且连带着加载其依赖的 Bean，而又因为 BeanPostProcessor 本身就需要对 Bean 进行处理，所以后加载的 BeanPostProcessor 是无法对之前加载的 BeanPostProcessor 以及其依赖 Bean 进行处理的。

确认步骤：
1. 在 `SofaRuntimeAutoConfiguration` 中的 `sofaRuntimeProperties` 打断点确认其加载时机（且可以通过调用栈找到其依赖方 `serviceAnnotationBeanPostProcessor`）
2. 在 `AbstractAutowireCapableBeanFactory` 中的 `applyBeanPostProcessorsBeforeInitialization` 进行条件断点，确认 `sofaRuntimeProperties` 被 PostProcessor 处理时 `ConfigurationPropertiesBindingPostProcessor` 是否存在，理论其不存在则不会注入配置

如果是我会尝试去掉在 BeanPostProcessor 中使用 `@ConfigurationProperties` 不知道你们有什么更好的建议，我会尝试修复这个问题以及补充一些测试。

**Comment by QilongZhang** [comment]
非常感谢，你的分析是对的。 `ServiceAnnotationBeanPostProcessor` 对 `sofaRuntimeProperties` 的依赖在另一个即将提的PR中已经剥离了，剥离的原因是因为开发另一个特性，碰巧也把你指出的这个问题规避了。 不过仍然非常希望你针对这个问题给我们提Fix PR。

**Comment by ScienJus** [comment]
Hi @QilongZhang ，按照目前的现状，我认为最轻量级的方式就是解除 `ServiceAnnotationBeanPostProcessor` 对 `SofaRuntimeProperties ` 的强绑定，而是改为在执行时通过 `ApplicationContext(BeanFactory)#getBean` 的弱绑定。

不知道你是否认同这种修复方案，以及是否有更好的方案？没有的话我会提交一个 PR 以及补充一些简单的测试。

注：其实这个 case 还是影响面很小的，不过在 BeanPostProcessor 使用其他 Bean 导致的加载顺序问题一不小心就会发生，而且用户 debug 还会很麻烦，所以以这个 case 举例介绍下。

**Comment by QilongZhang** [comment]
@ScienJus  首先感谢。正常情况下，你说的解决方案是可行的。因为另一个在开发的特性，会有一个限制，`ReferenceComponent` 和  `ReferenceRegisterHelper` 这两个类，不能直接或间接使用到任何spring相关的类。 目前代码中这两个类都是直接使用 `SofaRuntimeProperties` 这个类，因为这个类会依赖spring相关类，因此需要剥离。你的方案只需要保证不违背这点限制就好了。

**Comment by ScienJus** [comment]
@QilongZhang 目前只是在 `ServiceAnnotationBeanPostProcessor` 中修改了获取 `SofaRuntimeProperties` 和 `SofaRuntimeContext`，基本没动其他类，所以应该不会影响对其他类的重构？上面提到的两个类的剥离应该 rebase 后不会有冲突，希望如此…
