### ISSUE TITLE
change ServiceFactoryBean getObject return value

### ISSUE THREAD

**Issue by caojie09** [alipay/sofa-boot#92]
getObject method and getObjectType  method of ServiceFactoryBean: 

```java
@Override
public Object getObject() throws Exception {
    return ref;
}

@Override
public Class<?> getObjectType() {
    return ref != null ? ref.getClass() : Service.class;
}
```

we shouldn't return ref, it will make applicationContext.getBean(ref.getClass()) return more results.

**Comment by QilongZhang** [comment]
@caojie09  Fixed in https://github.com/alipay/sofa-boot/pull/97
