### ISSUE TITLE
SOFABoot health check don't import fastjson

### ISSUE THREAD

**Issue by guanchao-yang** [alipay/sofa-boot#94]
SOFABoot health check don't import fastjson

**Comment by QilongZhang** [comment]
Convert Map to JSON using Jackson instead of FastJson.

**Comment by khotyn** [comment]
为啥用 jackson 替代 fastjson，因为 jackson 是 SpringBoot 自带的依赖？

**Comment by guanchao-yang** [comment]
@khotyn 是的。Jackson 是 SpringBoot 默认依赖，我们也没有对 fastjson 某个功能的强依赖。所以选择  默认 jackson 即可了
