### ISSUE TITLE
It will lead some odd problems when get null from ReferenceFactoryBean#getObjectType

### ISSUE THREAD

**Issue by QilongZhang** [alipay/sofa-boot#95]
Currently,  it exists some situations where the invocation of  `com.alipay.sofa.runtime.spring.factory.ReferenceFactoryBean#getObjectType` would return null. As `ReferenceFactoryBean` is a `FactoryBean`,  this situation will make ReferenceFactoryBean to be created in advance and lead some odd problems. So,  we should avoid  occurrence of `null`.

**Comment by khotyn** [comment]
Could you describe what the problem is?
